<?xml version="1.0"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:message name="Msg_478d110cb5f6"/>
  <wsdl:message name="Msg_b1b89d22e733"/>
  <wsdl:message name="Msg_5db6cfa52551"/>
  <wsdl:message name="Msg_63fa46ec8d73"/>
  <wsdl:message name="Msg_a36314611af8"/>
  <wsdl:message name="Msg_8370f36e6323"/>
  <wsdl:message name="Msg_d65a52e9b7f8"/>
  <wsdl:message name="Msg_30c5ec6f35ff"/>
  <wsdl:message name="Msg_473b82193fc5"/>
  <wsdl:message name="Msg_7cd44703d6c9"/>
  <wsdl:message name="Msg_a7edebaa7ca9"/>
  <wsdl:message name="Msg_3d29ab0c0fc5"/>
  <wsdl:message name="Msg_64e89257b680"/>
  <wsdl:message name="Msg_70481baa40bc"/>
  <wsdl:message name="Msg_1c557703b8a1"/>
  <wsdl:message name="Msg_dd611fbadd4a"/>
  <wsdl:message name="Msg_e50cd0f0dc24"/>
  <wsdl:message name="Msg_6432c2101e1c"/>
  <wsdl:message name="Msg_2fac8ae419ec"/>
  <wsdl:message name="Msg_bc7f7e8a2ccb"/>
  <wsdl:message name="Msg_c50f162b1497"/>
  <wsdl:message name="Msg_f9f218f7b6be"/>
  <wsdl:message name="Msg_d74adb3fbf85"/>
  <wsdl:message name="Msg_a1173985f8c2"/>
  <wsdl:message name="Msg_a6f222fd0316"/>
  <wsdl:message name="Msg_68fb62c80caf"/>
  <wsdl:message name="Msg_cc95445c977f"/>
  <wsdl:message name="Msg_019e8a2a28f4"/>
  <wsdl:message name="Msg_b688a3705f8f"/>
  <wsdl:message name="Msg_87d442cc9b35"/>
  <wsdl:message name="Msg_9694ceab3b5b"/>
  <wsdl:message name="Msg_180889589807"/>
  <wsdl:message name="Msg_d146f6c04cfe"/>
  <wsdl:message name="Msg_c1cdb250ac77"/>
  <wsdl:message name="Msg_70597f1a1830"/>
  <wsdl:message name="Msg_3348eb68d45d"/>
  <wsdl:message name="Msg_87db75835bab"/>
  <wsdl:message name="Msg_3d3f18939217"/>
  <wsdl:message name="Msg_233674789a40"/>
  <wsdl:message name="Msg_6f888371fbab"/>
  <wsdl:message name="Msg_a7d46b6c662f"/>
  <wsdl:message name="Msg_9293d9ed937f"/>
  <wsdl:message name="Msg_d84195438225"/>
  <wsdl:message name="Msg_f5ab8d8b7321"/>
  <wsdl:message name="Msg_fdad4bacdfcd"/>
  <wsdl:message name="Msg_fa8d8273534d"/>
  <wsdl:message name="Msg_70015670e6a0"/>
  <wsdl:message name="Msg_c54307b8c7c8"/>
  <wsdl:message name="Msg_ffb72eccf4f7"/>
  <wsdl:message name="Msg_de185e82eb44"/>
  <wsdl:message name="Msg_103e11a4ae36"/>
  <wsdl:message name="Msg_7ad05ca3822a"/>
  <wsdl:message name="Msg_9f1e842a0b8d"/>
  <wsdl:message name="Msg_8ac5c6c95f76"/>
  <wsdl:message name="Msg_16019f2cf58a"/>
  <wsdl:message name="Msg_26dc850d38b4"/>
  <wsdl:message name="Msg_4a4786547ec8"/>
  <wsdl:message name="Msg_bbd2861eef9b"/>
  <wsdl:message name="Msg_4f769dfe3aa6"/>
  <wsdl:message name="Msg_aacf84cd48c2"/>
  <wsdl:message name="Msg_b1330bbd3cfb"/>
  <wsdl:message name="Msg_3fcc170dd354"/>
  <wsdl:message name="Msg_13de9ffc92d3"/>
  <wsdl:message name="Msg_45a76bf05f66"/>
  <wsdl:message name="Msg_86f4b86f30d0"/>
  <wsdl:message name="Msg_6caaa9d0bccc"/>
  <wsdl:message name="Msg_b53575f8379a"/>
  <wsdl:message name="Msg_4179bf4634a0"/>
  <wsdl:message name="Msg_d67e047d2745"/>
  <wsdl:message name="Msg_3dd823533f1c"/>
  <wsdl:message name="Msg_921735e4710f"/>
  <wsdl:message name="Msg_0d541fc7c1d7"/>
  <wsdl:message name="Msg_999377744e79"/>
  <wsdl:message name="Msg_60b5ea839ea1"/>
  <wsdl:message name="Msg_265305f3f368"/>
  <wsdl:message name="Msg_7bf8def2747c"/>
</wsdl:definitions>
