<?xml version="1.0"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:message name="Msg_437f033d77ad"/>
  <wsdl:message name="Msg_aa5a40c43877"/>
  <wsdl:message name="Msg_b6cad51457a6"/>
  <wsdl:message name="Msg_d8898f056b5e"/>
  <wsdl:message name="Msg_fe08a1823a36"/>
  <wsdl:message name="Msg_00ad3ae876f6"/>
  <wsdl:message name="Msg_8c135a57934f"/>
  <wsdl:message name="Msg_750f4bd6135f"/>
  <wsdl:message name="Msg_cb2dea9e1c03"/>
  <wsdl:message name="Msg_43dc960187d4"/>
  <wsdl:message name="Msg_842364422387"/>
  <wsdl:message name="Msg_5b13c645e3e1"/>
  <wsdl:message name="Msg_10c47342f19f"/>
  <wsdl:message name="Msg_144799c9f8c5"/>
  <wsdl:message name="Msg_a9fd154928f0"/>
  <wsdl:message name="Msg_4581c25dca07"/>
  <wsdl:message name="Msg_3cdd3b709158"/>
  <wsdl:message name="Msg_2c5d89ce0f0f"/>
  <wsdl:message name="Msg_4b3f9bfc89ad"/>
  <wsdl:message name="Msg_55a8bc05c898"/>
  <wsdl:message name="Msg_6d95d0bae770"/>
  <wsdl:message name="Msg_96cc671242df"/>
  <wsdl:message name="Msg_9631f955bcc4"/>
  <wsdl:message name="Msg_f7e898f01f4f"/>
  <wsdl:message name="Msg_a0f207774707"/>
  <wsdl:message name="Msg_57ac20caad66"/>
  <wsdl:message name="Msg_dd48ddf63603"/>
  <wsdl:message name="Msg_a055aef6f560"/>
  <wsdl:message name="Msg_4d1f742f8283"/>
  <wsdl:message name="Msg_545acf773914"/>
  <wsdl:message name="Msg_2dc67c367f63"/>
  <wsdl:message name="Msg_5532c254ba4a"/>
  <wsdl:message name="Msg_b90c9c8e9772"/>
  <wsdl:message name="Msg_202984c55794"/>
  <wsdl:message name="Msg_4864f8db4c3a"/>
  <wsdl:message name="Msg_7cff46fb9b5c"/>
  <wsdl:message name="Msg_5f2de9ab0172"/>
  <wsdl:message name="Msg_83e9a9a6cfdc"/>
  <wsdl:message name="Msg_3b153112fa3b"/>
</wsdl:definitions>
