<?xml version="1.0"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:message name="Msg_f2997112f8aa"/>
  <wsdl:message name="Msg_888ccda49888"/>
  <wsdl:message name="Msg_795ee419dd0e"/>
  <wsdl:message name="Msg_046dd291a140"/>
  <wsdl:message name="Msg_1d1e2353b62f"/>
  <wsdl:message name="Msg_68abc47c2d50"/>
  <wsdl:message name="Msg_7c33e9d732e0"/>
  <wsdl:message name="Msg_377c88f4744e"/>
  <wsdl:message name="Msg_d442ca7fbf3e"/>
  <wsdl:message name="Msg_df71b71fcd11"/>
  <wsdl:message name="Msg_ceef8d974dd6"/>
  <wsdl:message name="Msg_cda679c7d6c1"/>
  <wsdl:message name="Msg_e86ba39d6aa4"/>
  <wsdl:message name="Msg_e82c54bc9028"/>
  <wsdl:message name="Msg_f756ab92db39"/>
  <wsdl:message name="Msg_95757e5fe3f1"/>
  <wsdl:message name="Msg_1d19fcdc5207"/>
  <wsdl:message name="Msg_7e026a628428"/>
  <wsdl:message name="Msg_094e5404d280"/>
  <wsdl:message name="Msg_d68333f9e424"/>
  <wsdl:message name="Msg_6c65660b4bc9"/>
  <wsdl:message name="Msg_48881cb60bac"/>
  <wsdl:message name="Msg_566705b4aa65"/>
  <wsdl:message name="Msg_40ca304b1c1f"/>
  <wsdl:message name="Msg_12136467ae3b"/>
  <wsdl:message name="Msg_bfa19dffabf3"/>
  <wsdl:message name="Msg_634e1abdfa0f"/>
  <wsdl:message name="Msg_0af9dd38f94f"/>
  <wsdl:message name="Msg_45148d3e7280"/>
  <wsdl:message name="Msg_4ba3beb6bdef"/>
  <wsdl:message name="Msg_cce8be6e804b"/>
  <wsdl:message name="Msg_4f32fd9ead5b"/>
  <wsdl:message name="Msg_677e6da2bf67"/>
  <wsdl:message name="Msg_12ab205b2bea"/>
  <wsdl:message name="Msg_36df3c152199"/>
  <wsdl:message name="Msg_66c6328f15be"/>
  <wsdl:message name="Msg_2ff206da6b7c"/>
  <wsdl:message name="Msg_95819ee9fd10"/>
  <wsdl:message name="Msg_cbc7c055746c"/>
  <wsdl:message name="Msg_48c8db8c5b52"/>
  <wsdl:message name="Msg_32789bbb5763"/>
  <wsdl:message name="Msg_4704c4af69a4"/>
  <wsdl:message name="Msg_d5adb65cf588"/>
  <wsdl:message name="Msg_0b6a04d89e40"/>
  <wsdl:message name="Msg_e56c36d17767"/>
  <wsdl:message name="Msg_81946021b189"/>
  <wsdl:message name="Msg_944c8f53f726"/>
  <wsdl:message name="Msg_b8d9f761f51b"/>
  <wsdl:message name="Msg_1b8aed72759d"/>
  <wsdl:message name="Msg_0ead9bc9f240"/>
  <wsdl:message name="Msg_0554af9a7f8a"/>
  <wsdl:message name="Msg_3cea910f5aa3"/>
  <wsdl:message name="Msg_49db2ddf0f91"/>
  <wsdl:message name="Msg_939d9fb85170"/>
  <wsdl:message name="Msg_ac6e441a4589"/>
  <wsdl:message name="Msg_c679664e6898"/>
  <wsdl:message name="Msg_ba597c0800fe"/>
  <wsdl:message name="Msg_54905a5787cd"/>
  <wsdl:message name="Msg_9e27a0c9c2a7"/>
  <wsdl:message name="Msg_6f10c01f5427"/>
  <wsdl:message name="Msg_a486c8b32a0f"/>
  <wsdl:message name="Msg_778130b26642"/>
  <wsdl:message name="Msg_19b4793b3261"/>
  <wsdl:message name="Msg_af6d1ef7dff0"/>
  <wsdl:message name="Msg_43ba94fe4681"/>
  <wsdl:message name="Msg_d7c9f3101156"/>
  <wsdl:message name="Msg_f6549587ba21"/>
  <wsdl:message name="Msg_c4009af641d1"/>
  <wsdl:message name="Msg_1536302b1942"/>
  <wsdl:message name="Msg_ccd6d16a6a03"/>
  <wsdl:message name="Msg_0f60d14a168f"/>
  <wsdl:message name="Msg_43acb01ce427"/>
  <wsdl:message name="Msg_eaf0435062a2"/>
  <wsdl:message name="Msg_06dd48ba4b5a"/>
  <wsdl:message name="Msg_465a814fddea"/>
  <wsdl:message name="Msg_6a5d561ee488"/>
  <wsdl:message name="Msg_3716c9dcf345"/>
  <wsdl:message name="Msg_ed9691a7e34a"/>
  <wsdl:message name="Msg_8751fc66a045"/>
  <wsdl:message name="Msg_f77b33870063"/>
  <wsdl:message name="Msg_2dd79db36962"/>
  <wsdl:message name="Msg_d7fd42444377"/>
  <wsdl:message name="Msg_d2bb9c642649"/>
  <wsdl:message name="Msg_48c28748ff03"/>
  <wsdl:message name="Msg_d02d427d6d08"/>
  <wsdl:message name="Msg_d86b6e88ce44"/>
  <wsdl:message name="Msg_fb87c76793ca"/>
  <wsdl:message name="Msg_7be25a683d55"/>
  <wsdl:message name="Msg_f1e44186f8ed"/>
  <wsdl:message name="Msg_686565689b22"/>
  <wsdl:message name="Msg_61bad72b650d"/>
  <wsdl:message name="Msg_b98048c9be56"/>
  <wsdl:message name="Msg_6611bba2ba93"/>
  <wsdl:message name="Msg_931511d4944c"/>
  <wsdl:message name="Msg_1b43fefd298a"/>
  <wsdl:message name="Msg_cd68b7a3319f"/>
  <wsdl:message name="Msg_6bb89a921fa4"/>
  <wsdl:message name="Msg_5c9267058443"/>
  <wsdl:message name="Msg_0f00f8c6187d"/>
  <wsdl:message name="Msg_64bd14835a0f"/>
  <wsdl:message name="Msg_7430b32ffdac"/>
  <wsdl:message name="Msg_89a008c82088"/>
  <wsdl:message name="Msg_95834d45440c"/>
  <wsdl:message name="Msg_476cf99e5a6e"/>
  <wsdl:message name="Msg_404544df195e"/>
  <wsdl:message name="Msg_1bb1846b8fa0"/>
  <wsdl:message name="Msg_d4dd722ad488"/>
  <wsdl:message name="Msg_4039bc9b59f7"/>
  <wsdl:message name="Msg_f2f9764376db"/>
  <wsdl:message name="Msg_2faa275fe883"/>
  <wsdl:message name="Msg_8951c6ec94b8"/>
  <wsdl:message name="Msg_d4adb7851425"/>
  <wsdl:message name="Msg_cb0e025a572f"/>
  <wsdl:message name="Msg_aa2a6e569e3b"/>
  <wsdl:message name="Msg_ce943ced660b"/>
  <wsdl:message name="Msg_490c2205ab01"/>
  <wsdl:message name="Msg_38a2a0ae080d"/>
  <wsdl:message name="Msg_d75446af3287"/>
  <wsdl:message name="Msg_ce9ba0c52b4a"/>
  <wsdl:message name="Msg_4a170fb7badb"/>
  <wsdl:message name="Msg_880c4d8aee87"/>
  <wsdl:message name="Msg_743e17953960"/>
  <wsdl:message name="Msg_4a0cabc8f2ad"/>
  <wsdl:message name="Msg_4102788dd130"/>
  <wsdl:message name="Msg_1760816495e6"/>
  <wsdl:message name="Msg_fd00dd17e262"/>
  <wsdl:message name="Msg_543c16c3936c"/>
  <wsdl:message name="Msg_531fefd0c631"/>
  <wsdl:message name="Msg_2bc025968e4b"/>
  <wsdl:message name="Msg_f4587df33377"/>
  <wsdl:message name="Msg_3c04f99c6118"/>
  <wsdl:message name="Msg_937d849367d1"/>
  <wsdl:message name="Msg_9f3f0da4db94"/>
  <wsdl:message name="Msg_5d8868316b9b"/>
  <wsdl:message name="Msg_1e2c751301da"/>
  <wsdl:message name="Msg_fdb3c6a18f60"/>
  <wsdl:message name="Msg_03e957cb4ba3"/>
  <wsdl:message name="Msg_90e29312a891"/>
  <wsdl:message name="Msg_5ff8501d9c28"/>
  <wsdl:message name="Msg_8f6d9341a4cc"/>
  <wsdl:message name="Msg_e2c59a257f01"/>
  <wsdl:message name="Msg_f037ac994e0e"/>
  <wsdl:message name="Msg_a6736ed9273b"/>
  <wsdl:message name="Msg_89fba6ef51dd"/>
  <wsdl:message name="Msg_5faaab456d85"/>
  <wsdl:message name="Msg_141471e8c10b"/>
  <wsdl:message name="Msg_38e778a66874"/>
  <wsdl:message name="Msg_65420a2c4389"/>
  <wsdl:message name="Msg_42841a040215"/>
  <wsdl:message name="Msg_b972434cb3d4"/>
  <wsdl:message name="Msg_a1d71181328e"/>
  <wsdl:message name="Msg_d498181fc267"/>
  <wsdl:message name="Msg_4688acd92bcb"/>
  <wsdl:message name="Msg_8ad33d27db45"/>
  <wsdl:message name="Msg_4005b4bf365a"/>
  <wsdl:message name="Msg_8898607762ed"/>
  <wsdl:message name="Msg_b64933d188d3"/>
  <wsdl:message name="Msg_01bcbf8af561"/>
  <wsdl:message name="Msg_eba035bf100e"/>
  <wsdl:message name="Msg_908236f605e8"/>
  <wsdl:message name="Msg_6a18e4625b77"/>
  <wsdl:message name="Msg_10288f0d6e72"/>
  <wsdl:message name="Msg_357f715f5d20"/>
  <wsdl:message name="Msg_6b92138da6ed"/>
  <wsdl:message name="Msg_d0fb7df6556e"/>
  <wsdl:message name="Msg_50df30414b4b"/>
  <wsdl:message name="Msg_4ddaeb2a7f87"/>
  <wsdl:message name="Msg_9dc3bf08051c"/>
  <wsdl:message name="Msg_b76af1185149"/>
  <wsdl:message name="Msg_c8fb6ce2700e"/>
  <wsdl:message name="Msg_0f49230877cd"/>
  <wsdl:message name="Msg_9d044e60c118"/>
  <wsdl:message name="Msg_8b1f13dabeb5"/>
  <wsdl:message name="Msg_72f4acaa4bf8"/>
  <wsdl:message name="Msg_38eca2566e68"/>
  <wsdl:message name="Msg_a88a6d6692b6"/>
  <wsdl:message name="Msg_00cd1118caac"/>
  <wsdl:message name="Msg_e929f7189986"/>
  <wsdl:message name="Msg_3dbb28c096b0"/>
  <wsdl:message name="Msg_2106617ada12"/>
  <wsdl:message name="Msg_7a602a0250b0"/>
  <wsdl:message name="Msg_868c840b5c54"/>
  <wsdl:message name="Msg_542fb43c22ab"/>
  <wsdl:message name="Msg_668e105163f1"/>
  <wsdl:message name="Msg_39cae8bc6054"/>
  <wsdl:message name="Msg_00f02ca42081"/>
  <wsdl:message name="Msg_186f788138a6"/>
  <wsdl:message name="Msg_57ce7111b36d"/>
  <wsdl:message name="Msg_069ace48b1f9"/>
</wsdl:definitions>
