<?xml version="1.0"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:message name="Msg_b65187550f50"/>
  <wsdl:message name="Msg_6f2aad13613d"/>
  <wsdl:message name="Msg_be0633887e90"/>
  <wsdl:message name="Msg_eadf5de514c9"/>
  <wsdl:message name="Msg_34d646ec117b"/>
  <wsdl:message name="Msg_96410043ef21"/>
  <wsdl:message name="Msg_2a38df87f4e7"/>
  <wsdl:message name="Msg_e85975d7099a"/>
  <wsdl:message name="Msg_c6764ca652e1"/>
  <wsdl:message name="Msg_a0eaf4ae858f"/>
  <wsdl:message name="Msg_95c44d7fa2ad"/>
  <wsdl:message name="Msg_94d46a8913de"/>
  <wsdl:message name="Msg_d2544c371de5"/>
  <wsdl:message name="Msg_3d87ef9ee269"/>
  <wsdl:message name="Msg_fb7f2df1454a"/>
  <wsdl:message name="Msg_c4527b7d9865"/>
  <wsdl:message name="Msg_84a51d21c317"/>
  <wsdl:message name="Msg_2e27607c679b"/>
  <wsdl:message name="Msg_4e2f63433890"/>
  <wsdl:message name="Msg_da8a003d35c5"/>
  <wsdl:message name="Msg_42fc7b9c1f20"/>
  <wsdl:message name="Msg_4df9c6db632a"/>
  <wsdl:message name="Msg_38faa95352e0"/>
  <wsdl:message name="Msg_3453c072bf11"/>
  <wsdl:message name="Msg_1745b625c868"/>
  <wsdl:message name="Msg_5c77ccd7c50b"/>
  <wsdl:message name="Msg_e272187a8361"/>
  <wsdl:message name="Msg_cd72f88a5c04"/>
  <wsdl:message name="Msg_cde2b2013cc6"/>
  <wsdl:message name="Msg_b0f85737d551"/>
  <wsdl:message name="Msg_aa130c4f5446"/>
  <wsdl:message name="Msg_892f85e2092e"/>
  <wsdl:message name="Msg_157bd3c74857"/>
  <wsdl:message name="Msg_0527d59aa80c"/>
  <wsdl:message name="Msg_e9ae7b0df856"/>
  <wsdl:message name="Msg_b675dc1158b1"/>
  <wsdl:message name="Msg_43605a3021cc"/>
  <wsdl:message name="Msg_79b3b3411d06"/>
  <wsdl:message name="Msg_92b7175b6703"/>
  <wsdl:message name="Msg_a17c2bb583b7"/>
  <wsdl:message name="Msg_fcdf22da70b3"/>
  <wsdl:message name="Msg_bf3686c428e6"/>
  <wsdl:message name="Msg_60d66d57b43e"/>
  <wsdl:message name="Msg_a1ebbf419e7a"/>
  <wsdl:message name="Msg_1623a87a0b00"/>
  <wsdl:message name="Msg_25a758164687"/>
  <wsdl:message name="Msg_b3bb349b2993"/>
  <wsdl:message name="Msg_3ba053f65f3f"/>
  <wsdl:message name="Msg_f64a89338acc"/>
  <wsdl:message name="Msg_492b7a07dc46"/>
  <wsdl:message name="Msg_6911868e9fdf"/>
  <wsdl:message name="Msg_dc190de46928"/>
  <wsdl:message name="Msg_3720ba166998"/>
  <wsdl:message name="Msg_ef06a61b893e"/>
  <wsdl:message name="Msg_e23ba89655ba"/>
  <wsdl:message name="Msg_5f62824704c3"/>
  <wsdl:message name="Msg_006f11f50130"/>
  <wsdl:message name="Msg_89856b19a3ba"/>
  <wsdl:message name="Msg_f29eaaa49dae"/>
  <wsdl:message name="Msg_81ff94f75b44"/>
  <wsdl:message name="Msg_9c45658824b3"/>
  <wsdl:message name="Msg_bdf69c1ceead"/>
  <wsdl:message name="Msg_e25454096d49"/>
  <wsdl:message name="Msg_dd4da160b296"/>
  <wsdl:message name="Msg_058e68f572fd"/>
  <wsdl:message name="Msg_2275c6a1b4ee"/>
  <wsdl:message name="Msg_b3bac9222e69"/>
  <wsdl:message name="Msg_2029d2f079f5"/>
  <wsdl:message name="Msg_06a85a8a47b8"/>
  <wsdl:message name="Msg_16c54830fb9a"/>
  <wsdl:message name="Msg_3af307852fa0"/>
  <wsdl:message name="Msg_6dc795ffdded"/>
  <wsdl:message name="Msg_84110705e96b"/>
  <wsdl:message name="Msg_26c923f94155"/>
  <wsdl:message name="Msg_da8fcab917b4"/>
  <wsdl:message name="Msg_ee85aa265e45"/>
  <wsdl:message name="Msg_781d2cebef9f"/>
  <wsdl:message name="Msg_cc58fd0f32cf"/>
  <wsdl:message name="Msg_e3778533c7bf"/>
  <wsdl:message name="Msg_7f5400ce62e5"/>
  <wsdl:message name="Msg_771bb5e89909"/>
  <wsdl:message name="Msg_90321f01f389"/>
  <wsdl:message name="Msg_e5836a4f94cc"/>
  <wsdl:message name="Msg_138bf2aaac32"/>
  <wsdl:message name="Msg_7ad056ddd1d4"/>
  <wsdl:message name="Msg_ba09aeefe2c8"/>
  <wsdl:message name="Msg_02dbcda10af0"/>
  <wsdl:message name="Msg_cd747cac8a92"/>
  <wsdl:message name="Msg_afb7edcc6553"/>
  <wsdl:message name="Msg_c05cf8426a89"/>
  <wsdl:message name="Msg_22bce915274d"/>
  <wsdl:message name="Msg_cc8d5b95b4f4"/>
  <wsdl:message name="Msg_fd01fc0efba4"/>
  <wsdl:message name="Msg_8d183ebad460"/>
  <wsdl:message name="Msg_de07a68e682d"/>
  <wsdl:message name="Msg_918ba2d516fe"/>
  <wsdl:message name="Msg_e2066879f812"/>
  <wsdl:message name="Msg_532ebbea359e"/>
  <wsdl:message name="Msg_3611827a26af"/>
  <wsdl:message name="Msg_28aa94cd3387"/>
  <wsdl:message name="Msg_e7c158b577a3"/>
  <wsdl:message name="Msg_0fb9ab0e2829"/>
  <wsdl:message name="Msg_df1f1b541eeb"/>
  <wsdl:message name="Msg_f7b4b41b078c"/>
  <wsdl:message name="Msg_4cfb46973849"/>
  <wsdl:message name="Msg_a31b28eb8064"/>
  <wsdl:message name="Msg_28cf37570b69"/>
  <wsdl:message name="Msg_339be14a9d4e"/>
  <wsdl:message name="Msg_6f481707ebfa"/>
  <wsdl:message name="Msg_4d5dc95d5df5"/>
  <wsdl:message name="Msg_e3a7f671b918"/>
  <wsdl:message name="Msg_58d7a1ae2040"/>
  <wsdl:message name="Msg_ca1afbcf5145"/>
  <wsdl:message name="Msg_e90823979d58"/>
  <wsdl:message name="Msg_151a35cdc9a8"/>
  <wsdl:message name="Msg_5a9fc5e4ba9e"/>
  <wsdl:message name="Msg_9bdf98a1537f"/>
  <wsdl:message name="Msg_43d7c32fbfef"/>
  <wsdl:message name="Msg_b8af83582873"/>
  <wsdl:message name="Msg_9904b941ce08"/>
  <wsdl:message name="Msg_7083bc590e41"/>
  <wsdl:message name="Msg_e7e04966e484"/>
  <wsdl:message name="Msg_1b663b3f53ce"/>
  <wsdl:message name="Msg_969eaca6b649"/>
  <wsdl:message name="Msg_703d6e3518fe"/>
  <wsdl:message name="Msg_dd1ade3ae0c7"/>
  <wsdl:message name="Msg_8b0b36652d7a"/>
  <wsdl:message name="Msg_8cfe6a872efe"/>
  <wsdl:message name="Msg_788e8ed5516d"/>
  <wsdl:message name="Msg_60e5d727f02f"/>
  <wsdl:message name="Msg_2e494d562cf3"/>
  <wsdl:message name="Msg_83c6b2a10389"/>
  <wsdl:message name="Msg_c0a198db57b4"/>
  <wsdl:message name="Msg_cc45637f53b8"/>
  <wsdl:message name="Msg_efab7f13d986"/>
  <wsdl:message name="Msg_8ac24c054031"/>
  <wsdl:message name="Msg_8e39470cf1bd"/>
  <wsdl:message name="Msg_17da1dd6d2e2"/>
  <wsdl:message name="Msg_c8d446737047"/>
  <wsdl:message name="Msg_bbd4774901d1"/>
  <wsdl:message name="Msg_cacfecd98cc8"/>
  <wsdl:message name="Msg_d54a3977461a"/>
  <wsdl:message name="Msg_045d9cf5b9df"/>
  <wsdl:message name="Msg_8d4ed65f1385"/>
  <wsdl:message name="Msg_390d09f54398"/>
  <wsdl:message name="Msg_42e006d636cc"/>
  <wsdl:message name="Msg_8383624b0e50"/>
  <wsdl:message name="Msg_6d595ee2c5da"/>
  <wsdl:message name="Msg_a2fb33d8ce1b"/>
  <wsdl:message name="Msg_7e30df403049"/>
  <wsdl:message name="Msg_550e57458fd1"/>
  <wsdl:message name="Msg_ea56ae901e9b"/>
  <wsdl:message name="Msg_d8bd5742fb04"/>
  <wsdl:message name="Msg_7c6af11c4bd7"/>
  <wsdl:message name="Msg_65da29712596"/>
  <wsdl:message name="Msg_738ca2321586"/>
  <wsdl:message name="Msg_ece3f65c3e24"/>
  <wsdl:message name="Msg_2410a1ae2de1"/>
  <wsdl:message name="Msg_5ee209c12492"/>
  <wsdl:message name="Msg_1b1118734db7"/>
  <wsdl:message name="Msg_fefed00c9e9b"/>
  <wsdl:message name="Msg_50ac7b01160d"/>
  <wsdl:message name="Msg_13602852560c"/>
  <wsdl:message name="Msg_88d886fb07c7"/>
  <wsdl:message name="Msg_5f024b213b94"/>
  <wsdl:message name="Msg_8bd109672089"/>
  <wsdl:message name="Msg_08e725c79bec"/>
  <wsdl:message name="Msg_def40ca773c4"/>
  <wsdl:message name="Msg_8006b8ec1e65"/>
  <wsdl:message name="Msg_19bb23ccf21e"/>
  <wsdl:message name="Msg_01f120647023"/>
  <wsdl:message name="Msg_e1fe631f5f16"/>
  <wsdl:message name="Msg_e746cb7710de"/>
  <wsdl:message name="Msg_671d72f471ba"/>
  <wsdl:message name="Msg_c18c55aa22df"/>
  <wsdl:message name="Msg_37a48275ed9d"/>
  <wsdl:message name="Msg_f00f2d3f750b"/>
  <wsdl:message name="Msg_1dfebc01889a"/>
  <wsdl:message name="Msg_8bcf1493cac2"/>
  <wsdl:message name="Msg_5ce082c8e728"/>
  <wsdl:message name="Msg_404f6c13507f"/>
  <wsdl:message name="Msg_d75f53de5c44"/>
  <wsdl:message name="Msg_a62240e8f89c"/>
  <wsdl:message name="Msg_8e14b63d142e"/>
</wsdl:definitions>
