<?xml version="1.0"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:message name="Msg_4ea25a1944b4"/>
  <wsdl:message name="Msg_9ab010f47277"/>
  <wsdl:message name="Msg_748de8b2cfa1"/>
  <wsdl:message name="Msg_2f4f2385b0a0"/>
  <wsdl:message name="Msg_59955aba7636"/>
  <wsdl:message name="Msg_19737276947b"/>
  <wsdl:message name="Msg_aeb32f951ea4"/>
  <wsdl:message name="Msg_c7a3ee4fa534"/>
  <wsdl:message name="Msg_4839a86b758c"/>
  <wsdl:message name="Msg_4a0a6d6a49b6"/>
  <wsdl:message name="Msg_788823c59640"/>
  <wsdl:message name="Msg_cfade47e6a12"/>
  <wsdl:message name="Msg_2f4965cb1d4f"/>
  <wsdl:message name="Msg_0de29e7c025b"/>
  <wsdl:message name="Msg_ba7b5da50418"/>
  <wsdl:message name="Msg_c1b47c7194aa"/>
  <wsdl:message name="Msg_8f0b64dcbbb6"/>
  <wsdl:message name="Msg_194b347d727e"/>
  <wsdl:message name="Msg_d65201413c02"/>
  <wsdl:message name="Msg_b44aa79d7ac6"/>
  <wsdl:message name="Msg_b57e50eed141"/>
  <wsdl:message name="Msg_1e5e619d9bf5"/>
  <wsdl:message name="Msg_a357a2a2aa0c"/>
  <wsdl:message name="Msg_c329c706c47f"/>
  <wsdl:message name="Msg_4f3087a4cbb2"/>
  <wsdl:message name="Msg_a34af1103225"/>
  <wsdl:message name="Msg_bfd82b903bea"/>
  <wsdl:message name="Msg_ee0dd5a8a7db"/>
  <wsdl:message name="Msg_1009faf0d903"/>
  <wsdl:message name="Msg_208110bdc6a6"/>
  <wsdl:message name="Msg_580f0ad4347e"/>
  <wsdl:message name="Msg_1937a197b09c"/>
  <wsdl:message name="Msg_c77a2f25b48c"/>
  <wsdl:message name="Msg_82371fbac33c"/>
  <wsdl:message name="Msg_ccc7a18adfd5"/>
  <wsdl:message name="Msg_d9653db845b9"/>
  <wsdl:message name="Msg_cd50553a33df"/>
  <wsdl:message name="Msg_14b5c2dad28f"/>
  <wsdl:message name="Msg_2c3bdea58377"/>
  <wsdl:message name="Msg_e4e2070ae2cb"/>
  <wsdl:message name="Msg_f115d4bd1738"/>
  <wsdl:message name="Msg_d8c966fe0609"/>
  <wsdl:message name="Msg_c4fa528bc2e7"/>
  <wsdl:message name="Msg_9ba6c07bc27d"/>
  <wsdl:message name="Msg_715b37242d0f"/>
  <wsdl:message name="Msg_860c2f2461d7"/>
  <wsdl:message name="Msg_3abf613c9b21"/>
  <wsdl:message name="Msg_9b4fdeca2ac6"/>
  <wsdl:message name="Msg_12fb11e1c54f"/>
  <wsdl:message name="Msg_6dda17fbaf6b"/>
  <wsdl:message name="Msg_9d24a71878fb"/>
  <wsdl:message name="Msg_d1f6522e572c"/>
  <wsdl:message name="Msg_197463229089"/>
  <wsdl:message name="Msg_4f1e51e8b0e2"/>
  <wsdl:message name="Msg_1e6340cdade8"/>
  <wsdl:message name="Msg_7804db495ea6"/>
  <wsdl:message name="Msg_3e5ad0a7da71"/>
  <wsdl:message name="Msg_e5a8e9d60a98"/>
  <wsdl:message name="Msg_c171de46cfa6"/>
  <wsdl:message name="Msg_e36c56666827"/>
  <wsdl:message name="Msg_1e8f857f99a7"/>
  <wsdl:message name="Msg_aa01962c3f8c"/>
  <wsdl:message name="Msg_3573524a8835"/>
  <wsdl:message name="Msg_487fc31e9086"/>
  <wsdl:message name="Msg_8ce0c44e1c92"/>
  <wsdl:message name="Msg_6810f4f4c150"/>
  <wsdl:message name="Msg_cdd8bf55f3b5"/>
  <wsdl:message name="Msg_183e523333c6"/>
  <wsdl:message name="Msg_9be066ec51e6"/>
  <wsdl:message name="Msg_be7c261bd4a7"/>
  <wsdl:message name="Msg_afb29fda7c2f"/>
  <wsdl:message name="Msg_6c6ce0dd076a"/>
  <wsdl:message name="Msg_cb0355b98d26"/>
  <wsdl:message name="Msg_63f137f3f9d0"/>
  <wsdl:message name="Msg_b3543f5e2f54"/>
  <wsdl:message name="Msg_10222d99d325"/>
  <wsdl:message name="Msg_b5d93dfcb4f6"/>
  <wsdl:message name="Msg_0a0a62259350"/>
  <wsdl:message name="Msg_729d4f42824d"/>
  <wsdl:message name="Msg_5216ed54316a"/>
  <wsdl:message name="Msg_d3ac69d2de9f"/>
  <wsdl:message name="Msg_5911743318c5"/>
  <wsdl:message name="Msg_ac13926c2c28"/>
  <wsdl:message name="Msg_12bde643b2bb"/>
  <wsdl:message name="Msg_4b1a1f2be17b"/>
  <wsdl:message name="Msg_e9de344d1612"/>
  <wsdl:message name="Msg_eaf4961064fe"/>
  <wsdl:message name="Msg_fbacacad2116"/>
  <wsdl:message name="Msg_8df77f0547db"/>
  <wsdl:message name="Msg_5de2467a131d"/>
  <wsdl:message name="Msg_90520ce0d3e8"/>
  <wsdl:message name="Msg_5f99021599e6"/>
  <wsdl:message name="Msg_4c0e246b30bf"/>
  <wsdl:message name="Msg_339cc05ee06b"/>
  <wsdl:message name="Msg_735624a4fdf4"/>
  <wsdl:message name="Msg_60446edc1f2a"/>
  <wsdl:message name="Msg_ba17d7402ff6"/>
  <wsdl:message name="Msg_973009c62529"/>
  <wsdl:message name="Msg_10207c4ca4c1"/>
  <wsdl:message name="Msg_7ab2be2fe61f"/>
  <wsdl:message name="Msg_67d044a6a398"/>
  <wsdl:message name="Msg_79f36db38a1f"/>
  <wsdl:message name="Msg_18e2f26b800e"/>
  <wsdl:message name="Msg_0c0930c9fbb1"/>
  <wsdl:message name="Msg_ccf851bb1bda"/>
  <wsdl:message name="Msg_4ec71dadc016"/>
  <wsdl:message name="Msg_ffb84610d514"/>
  <wsdl:message name="Msg_360ec87e9bbc"/>
  <wsdl:message name="Msg_c0a59cdfdbde"/>
  <wsdl:message name="Msg_d605a4b67a02"/>
  <wsdl:message name="Msg_b791873723b1"/>
  <wsdl:message name="Msg_efabd8ce7bf8"/>
  <wsdl:message name="Msg_db0752e61c7b"/>
  <wsdl:message name="Msg_46eca1f45f27"/>
  <wsdl:message name="Msg_3e501d5859fb"/>
  <wsdl:message name="Msg_f3dd818e6ce0"/>
  <wsdl:message name="Msg_4c49f2211c2f"/>
  <wsdl:message name="Msg_314d453a6429"/>
  <wsdl:message name="Msg_48735c434a32"/>
</wsdl:definitions>
