<?xml version="1.0"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:message name="Msg_47d08fe3f252"/>
  <wsdl:message name="Msg_b9f3d0aa685d"/>
  <wsdl:message name="Msg_1e9c52277673"/>
  <wsdl:message name="Msg_5419f47f69be"/>
  <wsdl:message name="Msg_0d9f10b2b8da"/>
  <wsdl:message name="Msg_4e0ebdd7f174"/>
  <wsdl:message name="Msg_58b3175a2a76"/>
  <wsdl:message name="Msg_3c17e1ffd695"/>
  <wsdl:message name="Msg_ddc1bf3307e4"/>
  <wsdl:message name="Msg_2fdaa245a971"/>
  <wsdl:message name="Msg_38eb56e83514"/>
  <wsdl:message name="Msg_c0e3af2c9a7d"/>
  <wsdl:message name="Msg_39a09bcc558c"/>
  <wsdl:message name="Msg_4002895c95c8"/>
  <wsdl:message name="Msg_2b81f61c347b"/>
  <wsdl:message name="Msg_b0dc301b1a88"/>
  <wsdl:message name="Msg_bf42b89aca26"/>
  <wsdl:message name="Msg_e01a2df53e3b"/>
  <wsdl:message name="Msg_db93c051923e"/>
  <wsdl:message name="Msg_bf620bc03913"/>
  <wsdl:message name="Msg_b90f9f91e27a"/>
  <wsdl:message name="Msg_bbb534ede052"/>
  <wsdl:message name="Msg_ae321c39cea9"/>
  <wsdl:message name="Msg_024c8fada860"/>
  <wsdl:message name="Msg_7e70ac33b6c5"/>
  <wsdl:message name="Msg_eda8ac98f5ac"/>
  <wsdl:message name="Msg_109aa1079011"/>
  <wsdl:message name="Msg_6e6a1fed0956"/>
  <wsdl:message name="Msg_13c5ec8f7c53"/>
  <wsdl:message name="Msg_8acc4aea6664"/>
  <wsdl:message name="Msg_76dcd32fc71e"/>
  <wsdl:message name="Msg_08200cc1a1b7"/>
  <wsdl:message name="Msg_db20f7b34ef5"/>
  <wsdl:message name="Msg_b467576c731b"/>
  <wsdl:message name="Msg_749829421b5b"/>
  <wsdl:message name="Msg_5045e7b0c1f4"/>
  <wsdl:message name="Msg_5876076d1e63"/>
  <wsdl:message name="Msg_aa3675dd7435"/>
  <wsdl:message name="Msg_3ce53be03c54"/>
  <wsdl:message name="Msg_e795985b2663"/>
  <wsdl:message name="Msg_e1d8eb387369"/>
  <wsdl:message name="Msg_a868256cf6a9"/>
  <wsdl:message name="Msg_251af2244085"/>
  <wsdl:message name="Msg_74aa4dcc29ff"/>
  <wsdl:message name="Msg_babbe2510c5a"/>
  <wsdl:message name="Msg_1eac558f5407"/>
  <wsdl:message name="Msg_053e01e64ba0"/>
  <wsdl:message name="Msg_165190ca3976"/>
  <wsdl:message name="Msg_bc4069d74c77"/>
  <wsdl:message name="Msg_4e14c34051d3"/>
  <wsdl:message name="Msg_2a7b9f745db2"/>
  <wsdl:message name="Msg_e926a579c10d"/>
  <wsdl:message name="Msg_d291fbc6275b"/>
  <wsdl:message name="Msg_93d9e3a71c2c"/>
  <wsdl:message name="Msg_b49703e554f2"/>
  <wsdl:message name="Msg_75c82d8fa3ce"/>
  <wsdl:message name="Msg_177add6687e2"/>
  <wsdl:message name="Msg_aaa82d7c35b0"/>
</wsdl:definitions>
