<?xml version="1.0"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:message name="Msg_dce584d1ff10"/>
  <wsdl:message name="Msg_f37176bbf20d"/>
  <wsdl:message name="Msg_dcceca541a7d"/>
  <wsdl:message name="Msg_499898d6f329"/>
  <wsdl:message name="Msg_102b36252541"/>
  <wsdl:message name="Msg_0d69b3863bdc"/>
  <wsdl:message name="Msg_2b9c34c2142d"/>
  <wsdl:message name="Msg_6a3d6feb97c9"/>
  <wsdl:message name="Msg_563283700881"/>
  <wsdl:message name="Msg_86a731623b84"/>
  <wsdl:message name="Msg_fccb8c668007"/>
  <wsdl:message name="Msg_0149828bcb52"/>
  <wsdl:message name="Msg_a01257d9ce42"/>
  <wsdl:message name="Msg_516c28915186"/>
  <wsdl:message name="Msg_16b54d454ee8"/>
  <wsdl:message name="Msg_7575602a41d8"/>
  <wsdl:message name="Msg_ab8626403776"/>
  <wsdl:message name="Msg_5eb293c5b6ce"/>
  <wsdl:message name="Msg_9898e13401b1"/>
  <wsdl:message name="Msg_69b59a9ce9f0"/>
  <wsdl:message name="Msg_fbbb21870750"/>
  <wsdl:message name="Msg_1bfb588ea4f9"/>
  <wsdl:message name="Msg_521b4ba010af"/>
  <wsdl:message name="Msg_0c0d34b322af"/>
  <wsdl:message name="Msg_20ae3a8c49b0"/>
  <wsdl:message name="Msg_d5c67f37ea24"/>
  <wsdl:message name="Msg_20a8c09f1926"/>
  <wsdl:message name="Msg_6714af03b474"/>
  <wsdl:message name="Msg_a5c01e7110c2"/>
  <wsdl:message name="Msg_5237b7f31a5e"/>
  <wsdl:message name="Msg_1ed96a8c2a98"/>
  <wsdl:message name="Msg_9739cc90eee7"/>
  <wsdl:message name="Msg_03e33c2c64dc"/>
  <wsdl:message name="Msg_d53324af7cc0"/>
  <wsdl:message name="Msg_2acbe42765c4"/>
  <wsdl:message name="Msg_d5845aa4111d"/>
  <wsdl:message name="Msg_59e5cb81aca8"/>
  <wsdl:message name="Msg_947072ff65fe"/>
  <wsdl:message name="Msg_f1c9779afbe1"/>
  <wsdl:message name="Msg_b0aed33e1368"/>
  <wsdl:message name="Msg_b74d63e8bf7b"/>
  <wsdl:message name="Msg_22c4a9af13cd"/>
  <wsdl:message name="Msg_926883996071"/>
  <wsdl:message name="Msg_1ca98f0b28b5"/>
  <wsdl:message name="Msg_2d55b25b79b9"/>
  <wsdl:message name="Msg_c6ed23893f90"/>
  <wsdl:message name="Msg_a511fbd422f0"/>
  <wsdl:message name="Msg_ce8ed816ac67"/>
  <wsdl:message name="Msg_513f2cc3b152"/>
  <wsdl:message name="Msg_029b1c79cd7a"/>
  <wsdl:message name="Msg_d9778cbfe162"/>
  <wsdl:message name="Msg_6b52acd20425"/>
  <wsdl:message name="Msg_39f583464afb"/>
  <wsdl:message name="Msg_b4e0be4340de"/>
  <wsdl:message name="Msg_71057485719d"/>
  <wsdl:message name="Msg_f208be8592b6"/>
  <wsdl:message name="Msg_6a2cd89593c3"/>
  <wsdl:message name="Msg_82b12f403103"/>
  <wsdl:message name="Msg_b6b5b33064fd"/>
  <wsdl:message name="Msg_12d6bfd29806"/>
  <wsdl:message name="Msg_c11528cafe62"/>
  <wsdl:message name="Msg_284c208c8ebd"/>
  <wsdl:message name="Msg_cd8b3d07ee7a"/>
  <wsdl:message name="Msg_9115adf5c0fd"/>
  <wsdl:message name="Msg_461ef8920029"/>
  <wsdl:message name="Msg_890617baea5a"/>
  <wsdl:message name="Msg_ae29677fc0f1"/>
  <wsdl:message name="Msg_d584b23a157d"/>
  <wsdl:message name="Msg_6b4e240b5774"/>
  <wsdl:message name="Msg_dd9300c33749"/>
  <wsdl:message name="Msg_4d783ba31d81"/>
  <wsdl:message name="Msg_a72e1c45b6c6"/>
  <wsdl:message name="Msg_5e252aa96d33"/>
  <wsdl:message name="Msg_1c22602cf48b"/>
  <wsdl:message name="Msg_0637d06dd1ed"/>
  <wsdl:message name="Msg_5869fc554b9c"/>
  <wsdl:message name="Msg_1e20115cec8a"/>
  <wsdl:message name="Msg_f0a2d498b6a2"/>
  <wsdl:message name="Msg_d6a90c592f34"/>
  <wsdl:message name="Msg_8acc8a65ced2"/>
  <wsdl:message name="Msg_83b4ed36d3b7"/>
  <wsdl:message name="Msg_bdd2f2ccaaf2"/>
  <wsdl:message name="Msg_22bf04ffd805"/>
  <wsdl:message name="Msg_e5a4090cb7c8"/>
  <wsdl:message name="Msg_7bdd1c8e99a8"/>
  <wsdl:message name="Msg_c345224791de"/>
  <wsdl:message name="Msg_878309d8f144"/>
  <wsdl:message name="Msg_7c5f3dbd6f36"/>
  <wsdl:message name="Msg_5e9ed63c73cf"/>
  <wsdl:message name="Msg_32ea8f161fa8"/>
  <wsdl:message name="Msg_9d39b82d3dbd"/>
  <wsdl:message name="Msg_06215e339e44"/>
  <wsdl:message name="Msg_774d5f4fca7f"/>
  <wsdl:message name="Msg_9b8db9032be7"/>
  <wsdl:message name="Msg_39ed2c702d7c"/>
  <wsdl:message name="Msg_713155c1243d"/>
  <wsdl:message name="Msg_87abf0230a71"/>
  <wsdl:message name="Msg_ca78e261e67a"/>
  <wsdl:message name="Msg_9b9e34280f84"/>
  <wsdl:message name="Msg_f62d97e42faa"/>
  <wsdl:message name="Msg_9adf5f068e2c"/>
  <wsdl:message name="Msg_0c0f1aed1018"/>
  <wsdl:message name="Msg_8b9a33777886"/>
  <wsdl:message name="Msg_51daab50d370"/>
  <wsdl:message name="Msg_91bbf48d7e1a"/>
  <wsdl:message name="Msg_83138ee1f544"/>
  <wsdl:message name="Msg_9bd3091bec4e"/>
  <wsdl:message name="Msg_01eab3bf9565"/>
  <wsdl:message name="Msg_30e0cb137a90"/>
  <wsdl:message name="Msg_db3e3f19bc7f"/>
  <wsdl:message name="Msg_acbd3b95e2a6"/>
  <wsdl:message name="Msg_b190c888ad7d"/>
  <wsdl:message name="Msg_18b8668d7072"/>
  <wsdl:message name="Msg_3f1ee1dfc547"/>
  <wsdl:message name="Msg_0a1ec239eb05"/>
  <wsdl:message name="Msg_cba28de6b01f"/>
  <wsdl:message name="Msg_a3c60a904d1d"/>
  <wsdl:message name="Msg_cf43db1b0028"/>
  <wsdl:message name="Msg_e273e32853bf"/>
  <wsdl:message name="Msg_0b7bc08f27e4"/>
  <wsdl:message name="Msg_104c6967526b"/>
  <wsdl:message name="Msg_cdc3743ce336"/>
  <wsdl:message name="Msg_86dabe0ed608"/>
  <wsdl:message name="Msg_a4075fabbe00"/>
  <wsdl:message name="Msg_1bddca4515a7"/>
  <wsdl:message name="Msg_331ef52574dd"/>
  <wsdl:message name="Msg_7ad7c646f98e"/>
  <wsdl:message name="Msg_08ed81f9d140"/>
  <wsdl:message name="Msg_24cad94854ed"/>
  <wsdl:message name="Msg_222c420f857f"/>
  <wsdl:message name="Msg_c5b9af37fdc1"/>
  <wsdl:message name="Msg_e325b9159b73"/>
  <wsdl:message name="Msg_ccd88220e107"/>
  <wsdl:message name="Msg_24c4ad01cbe3"/>
  <wsdl:message name="Msg_61c45be75835"/>
  <wsdl:message name="Msg_b44feb177618"/>
  <wsdl:message name="Msg_14fa2247dc28"/>
  <wsdl:message name="Msg_8f418505bb60"/>
  <wsdl:message name="Msg_0e2f2aa5168f"/>
  <wsdl:message name="Msg_7198a31fb99c"/>
  <wsdl:message name="Msg_ab2883c61c3d"/>
  <wsdl:message name="Msg_25594a8166ea"/>
  <wsdl:message name="Msg_9bd82bfe870d"/>
  <wsdl:message name="Msg_244e23efbcf1"/>
  <wsdl:message name="Msg_e76d645a04b4"/>
  <wsdl:message name="Msg_8898a7252c54"/>
  <wsdl:message name="Msg_8e49c25ccd7b"/>
  <wsdl:message name="Msg_71a13a7ab095"/>
  <wsdl:message name="Msg_eab32a04b971"/>
  <wsdl:message name="Msg_c72db776826c"/>
  <wsdl:message name="Msg_7a28b21945a4"/>
  <wsdl:message name="Msg_f0fe43665310"/>
  <wsdl:message name="Msg_6730d453a66e"/>
  <wsdl:message name="Msg_d479b4de2bd5"/>
  <wsdl:message name="Msg_6f4b3c30afda"/>
  <wsdl:message name="Msg_7f9d6540e4e9"/>
  <wsdl:message name="Msg_c23cad45a475"/>
  <wsdl:message name="Msg_063b7b0cfef7"/>
  <wsdl:message name="Msg_0bbb93d61a45"/>
  <wsdl:message name="Msg_21d07f738178"/>
  <wsdl:message name="Msg_ac37f3abce6f"/>
  <wsdl:message name="Msg_d4afa0128041"/>
  <wsdl:message name="Msg_cdfa4601c2e5"/>
  <wsdl:message name="Msg_b2c7ebb76bc8"/>
  <wsdl:message name="Msg_ac33963e0f3b"/>
  <wsdl:message name="Msg_39aafd4cc15f"/>
  <wsdl:message name="Msg_9621bd30621b"/>
  <wsdl:message name="Msg_7d60184e7412"/>
  <wsdl:message name="Msg_a29451cd896e"/>
  <wsdl:message name="Msg_c5cfa52f7db0"/>
</wsdl:definitions>
