<?xml version="1.0"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:message name="Msg_a1b16bffb604"/>
  <wsdl:message name="Msg_dda08d8194e7"/>
  <wsdl:message name="Msg_3ff56aace04f"/>
  <wsdl:message name="Msg_b80224c382c0"/>
  <wsdl:message name="Msg_d4afbeddebbe"/>
  <wsdl:message name="Msg_3a15e96fa964"/>
  <wsdl:message name="Msg_602e1f5a8fb8"/>
  <wsdl:message name="Msg_14acac1b2b82"/>
  <wsdl:message name="Msg_22848ec889fd"/>
  <wsdl:message name="Msg_22e23eee931c"/>
  <wsdl:message name="Msg_dc26637f7e1f"/>
  <wsdl:message name="Msg_a6f495a93143"/>
  <wsdl:message name="Msg_d0df7fc7bbbb"/>
  <wsdl:message name="Msg_9c7c758042e3"/>
  <wsdl:message name="Msg_fd65951bc971"/>
  <wsdl:message name="Msg_196d2ce4b8c5"/>
  <wsdl:message name="Msg_760be11a2e7e"/>
  <wsdl:message name="Msg_b9cea02127da"/>
  <wsdl:message name="Msg_3a53fdd8a05c"/>
  <wsdl:message name="Msg_5eeaa88de810"/>
  <wsdl:message name="Msg_b2a42fe7ff4b"/>
  <wsdl:message name="Msg_9824f93a7f41"/>
  <wsdl:message name="Msg_5f8cc1a475bb"/>
  <wsdl:message name="Msg_da1deca73764"/>
  <wsdl:message name="Msg_c9f318ba5039"/>
  <wsdl:message name="Msg_196e06709b1e"/>
  <wsdl:message name="Msg_82bde52e3303"/>
  <wsdl:message name="Msg_34051b7eb2ec"/>
  <wsdl:message name="Msg_66fb95431c58"/>
  <wsdl:message name="Msg_9de98b81421d"/>
  <wsdl:message name="Msg_449808c931c6"/>
  <wsdl:message name="Msg_480e63271fff"/>
  <wsdl:message name="Msg_704d8cacfd4d"/>
  <wsdl:message name="Msg_e19364f67604"/>
  <wsdl:message name="Msg_2f7267defdf3"/>
  <wsdl:message name="Msg_092678a2b2fc"/>
  <wsdl:message name="Msg_10e2359a6c28"/>
  <wsdl:message name="Msg_80d008df3dea"/>
  <wsdl:message name="Msg_f77587d2fc3b"/>
  <wsdl:message name="Msg_060c1a002d29"/>
  <wsdl:message name="Msg_a9231d137e76"/>
  <wsdl:message name="Msg_aa35d5b226e8"/>
  <wsdl:message name="Msg_9df171107aca"/>
  <wsdl:message name="Msg_0f2109840963"/>
  <wsdl:message name="Msg_026266b4f82b"/>
  <wsdl:message name="Msg_54799ed06262"/>
  <wsdl:message name="Msg_512898e2ebcf"/>
  <wsdl:message name="Msg_b963aa38835c"/>
  <wsdl:message name="Msg_4f2f14232456"/>
  <wsdl:message name="Msg_fc5e1b00cd75"/>
  <wsdl:message name="Msg_0ca626c70c6b"/>
  <wsdl:message name="Msg_95587d1bfbbd"/>
  <wsdl:message name="Msg_ff17f650ef39"/>
  <wsdl:message name="Msg_aa06e42373e7"/>
  <wsdl:message name="Msg_ba53a1756a7a"/>
  <wsdl:message name="Msg_c5099a6f3c36"/>
  <wsdl:message name="Msg_fa686483dc6d"/>
  <wsdl:message name="Msg_92b057c7dc86"/>
  <wsdl:message name="Msg_c9eef4812194"/>
  <wsdl:message name="Msg_abcd54423afa"/>
  <wsdl:message name="Msg_4191adc07dfe"/>
  <wsdl:message name="Msg_74780a9b8ca9"/>
  <wsdl:message name="Msg_f188a7a9654c"/>
  <wsdl:message name="Msg_949c2d0bd46e"/>
  <wsdl:message name="Msg_38b52b6b9bd5"/>
  <wsdl:message name="Msg_03d883e64d18"/>
  <wsdl:message name="Msg_82335c216a1f"/>
  <wsdl:message name="Msg_41b830b4a201"/>
  <wsdl:message name="Msg_dcf83b4ef9b2"/>
  <wsdl:message name="Msg_a6465b25086a"/>
  <wsdl:message name="Msg_f276db6236bc"/>
  <wsdl:message name="Msg_9a2d84cb2123"/>
  <wsdl:message name="Msg_069b46b927c3"/>
  <wsdl:message name="Msg_15c313767fe0"/>
  <wsdl:message name="Msg_3e15e1cd9c8b"/>
  <wsdl:message name="Msg_c4db8a52c53c"/>
  <wsdl:message name="Msg_31ca7190163a"/>
  <wsdl:message name="Msg_7521464d6c5c"/>
  <wsdl:message name="Msg_ef9111cae156"/>
  <wsdl:message name="Msg_28c8fb0d28fd"/>
  <wsdl:message name="Msg_c0449ba4f0d2"/>
  <wsdl:message name="Msg_bc8c14748b69"/>
  <wsdl:message name="Msg_e79809f9decf"/>
  <wsdl:message name="Msg_bb37066906bd"/>
  <wsdl:message name="Msg_dd5ba50c9d98"/>
  <wsdl:message name="Msg_2366fbbe6a28"/>
  <wsdl:message name="Msg_1e2025ab6a04"/>
  <wsdl:message name="Msg_b5c671acecdd"/>
  <wsdl:message name="Msg_cc07fd7aa556"/>
  <wsdl:message name="Msg_bb90dc98d1ff"/>
  <wsdl:message name="Msg_97675b9fc042"/>
  <wsdl:message name="Msg_60e5eaf887d8"/>
  <wsdl:message name="Msg_b4f48ed097cd"/>
  <wsdl:message name="Msg_22756cf2736d"/>
  <wsdl:message name="Msg_da027c4471d6"/>
  <wsdl:message name="Msg_03d17e615d56"/>
  <wsdl:message name="Msg_ee025fd1dfab"/>
  <wsdl:message name="Msg_149100c2d749"/>
  <wsdl:message name="Msg_704be14737de"/>
  <wsdl:message name="Msg_29e78fe801ae"/>
  <wsdl:message name="Msg_bdbaaf31eb8b"/>
  <wsdl:message name="Msg_c4732a245acb"/>
  <wsdl:message name="Msg_80d4b6ca7ce4"/>
  <wsdl:message name="Msg_583e0d08fa4d"/>
  <wsdl:message name="Msg_2523ed8dccfd"/>
  <wsdl:message name="Msg_29c1f384c41f"/>
  <wsdl:message name="Msg_f394f4c8b840"/>
  <wsdl:message name="Msg_03cc1fbd7f46"/>
  <wsdl:message name="Msg_86bd3cc744b3"/>
  <wsdl:message name="Msg_f93ea9f07c1d"/>
  <wsdl:message name="Msg_7258103a9b15"/>
  <wsdl:message name="Msg_919c82ed6dea"/>
  <wsdl:message name="Msg_edbbee109aa3"/>
  <wsdl:message name="Msg_3d7fc07bc834"/>
  <wsdl:message name="Msg_e693937ae0d1"/>
  <wsdl:message name="Msg_97dd4b40cf54"/>
  <wsdl:message name="Msg_9e939dfafaab"/>
  <wsdl:message name="Msg_1f907ee20399"/>
  <wsdl:message name="Msg_e9d4ac78cbe7"/>
  <wsdl:message name="Msg_ecc298bcfd03"/>
  <wsdl:message name="Msg_df9c1f058390"/>
  <wsdl:message name="Msg_e05ea4b7d058"/>
  <wsdl:message name="Msg_b5ba65da2d7f"/>
  <wsdl:message name="Msg_af0ed659905c"/>
  <wsdl:message name="Msg_56e7939c3ffa"/>
  <wsdl:message name="Msg_04c5392231b1"/>
  <wsdl:message name="Msg_75d0bc88f735"/>
  <wsdl:message name="Msg_c2dbf57bef1b"/>
  <wsdl:message name="Msg_4ee40e61a18d"/>
  <wsdl:message name="Msg_c1da901400a4"/>
  <wsdl:message name="Msg_d59d9ce7236d"/>
  <wsdl:message name="Msg_f539da837fc6"/>
  <wsdl:message name="Msg_e8b654d3f176"/>
  <wsdl:message name="Msg_0e65126ae5cc"/>
  <wsdl:message name="Msg_4b51135dd0bd"/>
  <wsdl:message name="Msg_6be17e3e3e67"/>
  <wsdl:message name="Msg_be7f1a17b41e"/>
  <wsdl:message name="Msg_42d915324d2c"/>
  <wsdl:message name="Msg_9f5fc536a574"/>
  <wsdl:message name="Msg_e35de6579dbc"/>
  <wsdl:message name="Msg_a46fac82aa0b"/>
  <wsdl:message name="Msg_858ca76d37df"/>
  <wsdl:message name="Msg_168789dfd84d"/>
  <wsdl:message name="Msg_ea0260eae008"/>
  <wsdl:message name="Msg_b151920045f5"/>
  <wsdl:message name="Msg_a08f8bc7f076"/>
  <wsdl:message name="Msg_60159cdeb7f5"/>
  <wsdl:message name="Msg_a3c0f881fb6c"/>
  <wsdl:message name="Msg_32f7089a5dd4"/>
  <wsdl:message name="Msg_fc2af3343920"/>
  <wsdl:message name="Msg_9d420ca9e63e"/>
  <wsdl:message name="Msg_a88207ef67ab"/>
  <wsdl:message name="Msg_3222d12af6fb"/>
  <wsdl:message name="Msg_85e6c524a5e7"/>
  <wsdl:message name="Msg_a22f18cccc3b"/>
  <wsdl:message name="Msg_261aa7c0ab2d"/>
  <wsdl:message name="Msg_aa31ee6df1f9"/>
  <wsdl:message name="Msg_6040543738aa"/>
  <wsdl:message name="Msg_1f11afa99c90"/>
  <wsdl:message name="Msg_391ea0fdfd3c"/>
  <wsdl:message name="Msg_dfd5042ba131"/>
  <wsdl:message name="Msg_c3484f9bfdb9"/>
  <wsdl:message name="Msg_27ab91e47523"/>
  <wsdl:message name="Msg_f6e541575412"/>
  <wsdl:message name="Msg_170d8021dde6"/>
  <wsdl:message name="Msg_e3be22b8ef95"/>
  <wsdl:message name="Msg_9c53df9b7033"/>
  <wsdl:message name="Msg_1dcc7d1c5291"/>
  <wsdl:message name="Msg_03d89b2dd65d"/>
  <wsdl:message name="Msg_655660eb573e"/>
  <wsdl:message name="Msg_d16f1fb0cbb5"/>
  <wsdl:message name="Msg_0e7b027f3174"/>
  <wsdl:message name="Msg_3bf170d35a08"/>
  <wsdl:message name="Msg_f8c39070f56b"/>
  <wsdl:message name="Msg_079b4103fdbd"/>
  <wsdl:message name="Msg_1d2bdcb323f2"/>
  <wsdl:message name="Msg_8e77dec6f04e"/>
  <wsdl:message name="Msg_88b64ba78a29"/>
  <wsdl:message name="Msg_44962468544f"/>
  <wsdl:message name="Msg_172751a9f5bd"/>
  <wsdl:message name="Msg_6c5f34bedfdd"/>
  <wsdl:message name="Msg_189189a1232e"/>
  <wsdl:message name="Msg_23bf1a979218"/>
</wsdl:definitions>
