<?xml version="1.0"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:message name="Msg_03509af454c5"/>
  <wsdl:message name="Msg_5c7da0824d05"/>
  <wsdl:message name="Msg_e0a4fd03b7e9"/>
  <wsdl:message name="Msg_ab7b9bdaf781"/>
  <wsdl:message name="Msg_6438734a539b"/>
  <wsdl:message name="Msg_1127ef817cc8"/>
  <wsdl:message name="Msg_8398c9e66599"/>
  <wsdl:message name="Msg_c29b88c243ea"/>
  <wsdl:message name="Msg_eee3ee0a460c"/>
  <wsdl:message name="Msg_75399741f30f"/>
  <wsdl:message name="Msg_2881c8659f4c"/>
  <wsdl:message name="Msg_4402a4a00c5c"/>
  <wsdl:message name="Msg_90a781f477b5"/>
  <wsdl:message name="Msg_afcd1d05a618"/>
  <wsdl:message name="Msg_d05043ba944b"/>
  <wsdl:message name="Msg_061a47678c2c"/>
  <wsdl:message name="Msg_eddeb94d3fd2"/>
  <wsdl:message name="Msg_a1296ba78366"/>
  <wsdl:message name="Msg_1635f05cc24d"/>
  <wsdl:message name="Msg_16d3364d8541"/>
  <wsdl:message name="Msg_ba4fa713477e"/>
  <wsdl:message name="Msg_72e1b12ee34c"/>
  <wsdl:message name="Msg_9583e4c0e86d"/>
  <wsdl:message name="Msg_9974fab08ff6"/>
  <wsdl:message name="Msg_2ff096860421"/>
  <wsdl:message name="Msg_974c35d00df5"/>
  <wsdl:message name="Msg_7803575513d9"/>
  <wsdl:message name="Msg_7d703c9e2278"/>
  <wsdl:message name="Msg_2b9e00cde3f9"/>
  <wsdl:message name="Msg_07380ad445b0"/>
  <wsdl:message name="Msg_311b0252b150"/>
  <wsdl:message name="Msg_b7b298569473"/>
  <wsdl:message name="Msg_70a86a71cd4f"/>
  <wsdl:message name="Msg_8fab09002e64"/>
  <wsdl:message name="Msg_eaaa0079eec7"/>
  <wsdl:message name="Msg_f5f12772ddf8"/>
  <wsdl:message name="Msg_b0e8f28867b3"/>
  <wsdl:message name="Msg_d1cdcdab344e"/>
  <wsdl:message name="Msg_5e6d7a74af76"/>
  <wsdl:message name="Msg_1501f95a5e5b"/>
  <wsdl:message name="Msg_3e86e1987c3d"/>
  <wsdl:message name="Msg_04410d4bbb8c"/>
  <wsdl:message name="Msg_500a4e18a4ff"/>
  <wsdl:message name="Msg_b9dc2cf8c7ec"/>
  <wsdl:message name="Msg_ed4337ce93d0"/>
  <wsdl:message name="Msg_12b071252540"/>
  <wsdl:message name="Msg_c642896f21df"/>
  <wsdl:message name="Msg_4a3eaa0679f6"/>
  <wsdl:message name="Msg_5577cc69e22d"/>
  <wsdl:message name="Msg_1cedd88a9f22"/>
  <wsdl:message name="Msg_1c4c51453120"/>
  <wsdl:message name="Msg_6264fecb8f0c"/>
  <wsdl:message name="Msg_0dea0a6a31a0"/>
  <wsdl:message name="Msg_629bc0ec3bbc"/>
  <wsdl:message name="Msg_cbaff47f9152"/>
  <wsdl:message name="Msg_1f6b283281b2"/>
  <wsdl:message name="Msg_afb9498dc312"/>
  <wsdl:message name="Msg_2cdfc168ded8"/>
  <wsdl:message name="Msg_384f4e33f9a5"/>
  <wsdl:message name="Msg_2573d4fd5862"/>
  <wsdl:message name="Msg_32e0a796fd11"/>
  <wsdl:message name="Msg_1550f037d3fc"/>
  <wsdl:message name="Msg_f9fefe8b7549"/>
  <wsdl:message name="Msg_d4db7a2b2147"/>
  <wsdl:message name="Msg_9ff79eea1c47"/>
  <wsdl:message name="Msg_704486772b91"/>
  <wsdl:message name="Msg_90acfb6061ef"/>
  <wsdl:message name="Msg_b68617ee8bea"/>
</wsdl:definitions>
