<?xml version="1.0"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:message name="Msg_ef683d070cf8"/>
  <wsdl:message name="Msg_6f20fca563fc"/>
  <wsdl:message name="Msg_116ce9bc1291"/>
  <wsdl:message name="Msg_795245b3b82e"/>
  <wsdl:message name="Msg_39d2b1237389"/>
  <wsdl:message name="Msg_c56b31a6af22"/>
  <wsdl:message name="Msg_5764d132aa40"/>
  <wsdl:message name="Msg_091be336ace1"/>
  <wsdl:message name="Msg_bf733e51fc41"/>
  <wsdl:message name="Msg_848bae7dd075"/>
  <wsdl:message name="Msg_20b4fc7dbd77"/>
  <wsdl:message name="Msg_b450bf6348c1"/>
  <wsdl:message name="Msg_a6414d4c5e3c"/>
  <wsdl:message name="Msg_511be5a2373a"/>
  <wsdl:message name="Msg_0af388beaf70"/>
  <wsdl:message name="Msg_72b658c2d24c"/>
  <wsdl:message name="Msg_892ab1d10e05"/>
  <wsdl:message name="Msg_dec80cf30c11"/>
  <wsdl:message name="Msg_96f2c5b0c891"/>
  <wsdl:message name="Msg_e4c44feacf47"/>
  <wsdl:message name="Msg_6b3bff21977a"/>
  <wsdl:message name="Msg_a096889f2e9c"/>
  <wsdl:message name="Msg_702bdb4e6e10"/>
  <wsdl:message name="Msg_125c232702d6"/>
  <wsdl:message name="Msg_9a7b27240e28"/>
  <wsdl:message name="Msg_f8d9b95f362f"/>
  <wsdl:message name="Msg_df714cb59e05"/>
  <wsdl:message name="Msg_c12ad6ea6184"/>
  <wsdl:message name="Msg_93c128212e1a"/>
  <wsdl:message name="Msg_e95e95ba55b7"/>
  <wsdl:message name="Msg_97af3f207e95"/>
  <wsdl:message name="Msg_77fe11393f54"/>
  <wsdl:message name="Msg_ba5016afdf19"/>
  <wsdl:message name="Msg_338e8ec0ae02"/>
  <wsdl:message name="Msg_326a19fb2259"/>
  <wsdl:message name="Msg_1807ba4d87bd"/>
  <wsdl:message name="Msg_75c9bc72bb5b"/>
  <wsdl:message name="Msg_4575df31f6bc"/>
  <wsdl:message name="Msg_f8fae05e4420"/>
  <wsdl:message name="Msg_7159064f3082"/>
  <wsdl:message name="Msg_808abb819f3f"/>
  <wsdl:message name="Msg_f78573ed1558"/>
  <wsdl:message name="Msg_a6d65852aee6"/>
  <wsdl:message name="Msg_3dac8b0634db"/>
  <wsdl:message name="Msg_4a0e530604c3"/>
  <wsdl:message name="Msg_03455b1afe19"/>
  <wsdl:message name="Msg_e1793eaa438a"/>
  <wsdl:message name="Msg_cb386263ba6a"/>
  <wsdl:message name="Msg_b184ba0cea04"/>
  <wsdl:message name="Msg_190b4698429b"/>
  <wsdl:message name="Msg_4b96cede2dff"/>
  <wsdl:message name="Msg_b3f047eaad2c"/>
  <wsdl:message name="Msg_16202ffed539"/>
  <wsdl:message name="Msg_737786c644f9"/>
  <wsdl:message name="Msg_9a913943dcd1"/>
  <wsdl:message name="Msg_3988dfe28e70"/>
  <wsdl:message name="Msg_c7d7b0c7d0ec"/>
  <wsdl:message name="Msg_3a0f34372942"/>
  <wsdl:message name="Msg_e5884adf7596"/>
  <wsdl:message name="Msg_038761155adc"/>
  <wsdl:message name="Msg_f03a4890d88a"/>
  <wsdl:message name="Msg_10a2b9fdf6e6"/>
  <wsdl:message name="Msg_1c6358e75107"/>
  <wsdl:message name="Msg_067af64b0da9"/>
  <wsdl:message name="Msg_3473623d682f"/>
</wsdl:definitions>
