<?xml version="1.0"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:message name="Msg_d190cdabadae"/>
  <wsdl:message name="Msg_c8349cf6cbfd"/>
  <wsdl:message name="Msg_1822d8d05fab"/>
  <wsdl:message name="Msg_06108f1e15a9"/>
  <wsdl:message name="Msg_a8e63c2dd04a"/>
  <wsdl:message name="Msg_0ede3d590e2d"/>
  <wsdl:message name="Msg_1e01a1c41f40"/>
  <wsdl:message name="Msg_547e0fa7f110"/>
  <wsdl:message name="Msg_ec5ae628ee4b"/>
  <wsdl:message name="Msg_87b04093f626"/>
  <wsdl:message name="Msg_133b31bcd130"/>
  <wsdl:message name="Msg_1365063d4fdc"/>
  <wsdl:message name="Msg_52933aa64df8"/>
  <wsdl:message name="Msg_3c88ce3ea55d"/>
  <wsdl:message name="Msg_573b75b2ceee"/>
  <wsdl:message name="Msg_0de304d3ca55"/>
  <wsdl:message name="Msg_b3691ac099f1"/>
  <wsdl:message name="Msg_ad5d3238d34b"/>
  <wsdl:message name="Msg_015392064286"/>
  <wsdl:message name="Msg_55911964ed5f"/>
  <wsdl:message name="Msg_d0e7b27c600d"/>
  <wsdl:message name="Msg_7e7ebc8fd8b5"/>
  <wsdl:message name="Msg_5138fb193f7d"/>
  <wsdl:message name="Msg_282824603623"/>
  <wsdl:message name="Msg_c48ec2940e9c"/>
  <wsdl:message name="Msg_9b77e352dd1f"/>
  <wsdl:message name="Msg_4078624e8f60"/>
  <wsdl:message name="Msg_2250b932d8f7"/>
  <wsdl:message name="Msg_e506b207f3f0"/>
  <wsdl:message name="Msg_6b58f04e5d9a"/>
  <wsdl:message name="Msg_996b6290a3c9"/>
  <wsdl:message name="Msg_1bba0454c075"/>
  <wsdl:message name="Msg_6105736aef71"/>
  <wsdl:message name="Msg_095859d71847"/>
  <wsdl:message name="Msg_512d3781a977"/>
  <wsdl:message name="Msg_dfb648cf4a64"/>
  <wsdl:message name="Msg_41d40291203e"/>
  <wsdl:message name="Msg_af150e51e92e"/>
  <wsdl:message name="Msg_07211599b80d"/>
  <wsdl:message name="Msg_a63c5baa311c"/>
  <wsdl:message name="Msg_7bda43bdeb16"/>
  <wsdl:message name="Msg_f305e0c2137b"/>
  <wsdl:message name="Msg_1c8af00e214d"/>
  <wsdl:message name="Msg_1f71bac30d73"/>
  <wsdl:message name="Msg_96ce18646212"/>
  <wsdl:message name="Msg_fc8d03506eb4"/>
  <wsdl:message name="Msg_a417f6e41661"/>
  <wsdl:message name="Msg_459c891a03d5"/>
  <wsdl:message name="Msg_48d0aea84c8a"/>
  <wsdl:message name="Msg_1d3d98c99205"/>
  <wsdl:message name="Msg_4d8daf3c3b3a"/>
  <wsdl:message name="Msg_51ed4b223ebc"/>
  <wsdl:message name="Msg_685c825ad390"/>
  <wsdl:message name="Msg_6131b03341e5"/>
  <wsdl:message name="Msg_e39672aa6947"/>
  <wsdl:message name="Msg_7b06f34eb3c6"/>
  <wsdl:message name="Msg_da90b7b9ac52"/>
  <wsdl:message name="Msg_e41a84303e31"/>
  <wsdl:message name="Msg_e90d930634d5"/>
  <wsdl:message name="Msg_dff488def7e9"/>
  <wsdl:message name="Msg_d3c9d224a304"/>
</wsdl:definitions>
