<?xml version="1.0"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:message name="Msg_0b72c11af20b"/>
  <wsdl:message name="Msg_cee38f14f795"/>
  <wsdl:message name="Msg_ee316ecfbfb5"/>
  <wsdl:message name="Msg_96a4ff75fa58"/>
  <wsdl:message name="Msg_131efc5294a9"/>
  <wsdl:message name="Msg_48a49e388273"/>
  <wsdl:message name="Msg_da20a8db6fe4"/>
  <wsdl:message name="Msg_0c96f41c2749"/>
  <wsdl:message name="Msg_263ed35c2447"/>
  <wsdl:message name="Msg_9e52a9aabd66"/>
  <wsdl:message name="Msg_e634e67f7fef"/>
  <wsdl:message name="Msg_af33fd7fdccd"/>
  <wsdl:message name="Msg_f78a40c34438"/>
  <wsdl:message name="Msg_66ab1f28f64c"/>
  <wsdl:message name="Msg_6577b7342959"/>
  <wsdl:message name="Msg_5dff24da6ae8"/>
  <wsdl:message name="Msg_a1716c582cc0"/>
  <wsdl:message name="Msg_bc26211cd6c7"/>
  <wsdl:message name="Msg_93ff003da0a2"/>
  <wsdl:message name="Msg_166a7ccef4f3"/>
  <wsdl:message name="Msg_060bbb5f230e"/>
  <wsdl:message name="Msg_86e379db978d"/>
  <wsdl:message name="Msg_4d0deb12c9f2"/>
  <wsdl:message name="Msg_de592fd3a410"/>
  <wsdl:message name="Msg_484297c1cdab"/>
  <wsdl:message name="Msg_7a89fdf5bb84"/>
  <wsdl:message name="Msg_1063a0f41f8a"/>
  <wsdl:message name="Msg_10f2ca052039"/>
  <wsdl:message name="Msg_7f9406d23649"/>
  <wsdl:message name="Msg_6ec0abf2db8b"/>
  <wsdl:message name="Msg_fbd436fbaa1c"/>
  <wsdl:message name="Msg_601fd5d94efd"/>
  <wsdl:message name="Msg_926001d6681f"/>
  <wsdl:message name="Msg_fb08ee0432f8"/>
  <wsdl:message name="Msg_02aee565d4a7"/>
  <wsdl:message name="Msg_fa65c09498a8"/>
  <wsdl:message name="Msg_4dec09c918ae"/>
  <wsdl:message name="Msg_aa5147635932"/>
  <wsdl:message name="Msg_816e1a659310"/>
  <wsdl:message name="Msg_02d628c314e0"/>
  <wsdl:message name="Msg_898b4b7c48c1"/>
  <wsdl:message name="Msg_fa5d43c728b6"/>
  <wsdl:message name="Msg_f482a2b04c4c"/>
  <wsdl:message name="Msg_3ad0e9a50ec5"/>
  <wsdl:message name="Msg_799824edd668"/>
  <wsdl:message name="Msg_9b9ab9500aa8"/>
  <wsdl:message name="Msg_e9a6d02dc3dd"/>
  <wsdl:message name="Msg_6f6d049c0428"/>
  <wsdl:message name="Msg_f61178f6bf0e"/>
  <wsdl:message name="Msg_230ebe1cfd94"/>
  <wsdl:message name="Msg_1f87fcdd6b8b"/>
  <wsdl:message name="Msg_9e25ec0021dc"/>
  <wsdl:message name="Msg_83b78ed13b28"/>
  <wsdl:message name="Msg_cd3d5d122eef"/>
  <wsdl:message name="Msg_b68cbb1accd9"/>
  <wsdl:message name="Msg_86a5568852a5"/>
  <wsdl:message name="Msg_76d5f770dc7b"/>
  <wsdl:message name="Msg_f57037696950"/>
  <wsdl:message name="Msg_88c1d71a869a"/>
  <wsdl:message name="Msg_01d4bf94eadb"/>
  <wsdl:message name="Msg_d4fa9de80a71"/>
  <wsdl:message name="Msg_468dfb92be23"/>
  <wsdl:message name="Msg_3214072d0268"/>
  <wsdl:message name="Msg_e06b27373ec4"/>
  <wsdl:message name="Msg_8079e538db94"/>
  <wsdl:message name="Msg_6b7a3a2bc0e2"/>
  <wsdl:message name="Msg_bdb0e6d8dc34"/>
  <wsdl:message name="Msg_3b7442353259"/>
  <wsdl:message name="Msg_a4acc43a630c"/>
  <wsdl:message name="Msg_fcf44475a28d"/>
  <wsdl:message name="Msg_f2324809ab9b"/>
  <wsdl:message name="Msg_6dc5ffbc4a05"/>
  <wsdl:message name="Msg_b9817bd1b96c"/>
  <wsdl:message name="Msg_13a55f071774"/>
  <wsdl:message name="Msg_a8d0f26572f1"/>
  <wsdl:message name="Msg_bca930427119"/>
  <wsdl:message name="Msg_69233ddc9280"/>
  <wsdl:message name="Msg_dc0670abdcff"/>
  <wsdl:message name="Msg_c18ee72120ef"/>
  <wsdl:message name="Msg_d26e7fbebad3"/>
  <wsdl:message name="Msg_d0dcc2a16351"/>
  <wsdl:message name="Msg_b63691ae061c"/>
  <wsdl:message name="Msg_b1261f709949"/>
  <wsdl:message name="Msg_9ffc785b8916"/>
  <wsdl:message name="Msg_3410a911edfa"/>
  <wsdl:message name="Msg_afcc96e0ea28"/>
  <wsdl:message name="Msg_87c58ba2dca2"/>
  <wsdl:message name="Msg_2135826b5f68"/>
  <wsdl:message name="Msg_27e67975c7a2"/>
  <wsdl:message name="Msg_63b588470eb3"/>
  <wsdl:message name="Msg_0784cd6204e8"/>
  <wsdl:message name="Msg_209d221a8fc8"/>
  <wsdl:message name="Msg_d4edbeeb23b3"/>
  <wsdl:message name="Msg_57f1cdffd13b"/>
  <wsdl:message name="Msg_3fc744b0c345"/>
  <wsdl:message name="Msg_3efdc8e3fa7a"/>
  <wsdl:message name="Msg_4fab638e7fd8"/>
  <wsdl:message name="Msg_5a8f437a3849"/>
  <wsdl:message name="Msg_bfae37f9b068"/>
  <wsdl:message name="Msg_49a424123a9c"/>
  <wsdl:message name="Msg_bbc2f8f82844"/>
  <wsdl:message name="Msg_ee2418f5b672"/>
  <wsdl:message name="Msg_a2b1469f2591"/>
  <wsdl:message name="Msg_411cde5b94e3"/>
  <wsdl:message name="Msg_d949fb09f314"/>
  <wsdl:message name="Msg_f76cf2d53200"/>
  <wsdl:message name="Msg_4fd09919e740"/>
  <wsdl:message name="Msg_bae2264c035d"/>
  <wsdl:message name="Msg_cf41a5789b2d"/>
  <wsdl:message name="Msg_83c548d3921c"/>
  <wsdl:message name="Msg_054639f72e61"/>
  <wsdl:message name="Msg_580a5849e83e"/>
  <wsdl:message name="Msg_8992bcc273dd"/>
  <wsdl:message name="Msg_6c1a78180a3e"/>
  <wsdl:message name="Msg_6328e8a07f6e"/>
  <wsdl:message name="Msg_88a04e030970"/>
  <wsdl:message name="Msg_76c3ecdb1bf3"/>
  <wsdl:message name="Msg_27a0a9ee2d6e"/>
  <wsdl:message name="Msg_39f7ecee61e1"/>
  <wsdl:message name="Msg_1ebb53786b41"/>
  <wsdl:message name="Msg_e367bae11e67"/>
  <wsdl:message name="Msg_0412adec8dea"/>
  <wsdl:message name="Msg_944a41fa9d12"/>
  <wsdl:message name="Msg_e6e1bad69860"/>
  <wsdl:message name="Msg_7f8b3accf000"/>
  <wsdl:message name="Msg_95360907ab2c"/>
  <wsdl:message name="Msg_a532b17880e2"/>
  <wsdl:message name="Msg_45fddef36152"/>
  <wsdl:message name="Msg_9565a42eb35b"/>
  <wsdl:message name="Msg_ab153c1ea8dc"/>
  <wsdl:message name="Msg_575d4ca03c61"/>
  <wsdl:message name="Msg_8f95b11a2507"/>
  <wsdl:message name="Msg_43b7d4e759af"/>
  <wsdl:message name="Msg_1e32a2f98841"/>
  <wsdl:message name="Msg_0b46f9cd7991"/>
  <wsdl:message name="Msg_03396c5f64f9"/>
  <wsdl:message name="Msg_73f31b93a2cc"/>
  <wsdl:message name="Msg_2e132cfd1ef4"/>
  <wsdl:message name="Msg_a88bfb0f2813"/>
  <wsdl:message name="Msg_5da724a52067"/>
  <wsdl:message name="Msg_eee1d7d1a726"/>
  <wsdl:message name="Msg_4ee5777e3ecf"/>
  <wsdl:message name="Msg_93ba621d2fdd"/>
  <wsdl:message name="Msg_9ded8c96a70f"/>
  <wsdl:message name="Msg_b3598f8b5cfe"/>
  <wsdl:message name="Msg_7cb347bed347"/>
  <wsdl:message name="Msg_f22fcc493c3d"/>
  <wsdl:message name="Msg_15262751d0ec"/>
  <wsdl:message name="Msg_c722527cb0db"/>
  <wsdl:message name="Msg_533dfd69a34a"/>
  <wsdl:message name="Msg_7c015e435842"/>
  <wsdl:message name="Msg_931dec0515f3"/>
  <wsdl:message name="Msg_659e7321f7a2"/>
  <wsdl:message name="Msg_c51abab2159f"/>
  <wsdl:message name="Msg_2e2c1adb5ecb"/>
  <wsdl:message name="Msg_60f3c7dd981d"/>
  <wsdl:message name="Msg_45a916c9a0e9"/>
  <wsdl:message name="Msg_4ebdc28e0cef"/>
  <wsdl:message name="Msg_6eadbc6f94b2"/>
</wsdl:definitions>
