<?xml version="1.0"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:message name="Msg_157a23cd0170"/>
  <wsdl:message name="Msg_e8372bd5514b"/>
  <wsdl:message name="Msg_c447ae48ed5c"/>
  <wsdl:message name="Msg_182ad36da251"/>
  <wsdl:message name="Msg_1ac71762c86a"/>
  <wsdl:message name="Msg_11f20a26ea96"/>
  <wsdl:message name="Msg_1312916f1682"/>
  <wsdl:message name="Msg_6f90d900abe6"/>
  <wsdl:message name="Msg_555338fba064"/>
  <wsdl:message name="Msg_58f9d588d6c3"/>
  <wsdl:message name="Msg_93a97e7f87a8"/>
  <wsdl:message name="Msg_0564543bc18e"/>
  <wsdl:message name="Msg_b81b27da9a12"/>
  <wsdl:message name="Msg_48fe1bdd862e"/>
  <wsdl:message name="Msg_eeae76153790"/>
  <wsdl:message name="Msg_1a7aad2acb3e"/>
  <wsdl:message name="Msg_e9755ee3cdb9"/>
  <wsdl:message name="Msg_68c8145fcf1b"/>
  <wsdl:message name="Msg_fbde05d50431"/>
  <wsdl:message name="Msg_e7044d226ec4"/>
  <wsdl:message name="Msg_9cb8e2c1a6c0"/>
  <wsdl:message name="Msg_7edb53bc2533"/>
  <wsdl:message name="Msg_5641f605b968"/>
  <wsdl:message name="Msg_b830c24ba3b9"/>
  <wsdl:message name="Msg_fd7eefffd33b"/>
  <wsdl:message name="Msg_4b85560117ce"/>
  <wsdl:message name="Msg_c1ceeafffe94"/>
  <wsdl:message name="Msg_5e88bc1f1322"/>
  <wsdl:message name="Msg_4935736a2f8f"/>
  <wsdl:message name="Msg_beb6b8841fa3"/>
  <wsdl:message name="Msg_68ce48d88db4"/>
  <wsdl:message name="Msg_a650895990ce"/>
  <wsdl:message name="Msg_c3686f4a5f99"/>
  <wsdl:message name="Msg_ae466320d353"/>
  <wsdl:message name="Msg_d7ccced16dd7"/>
  <wsdl:message name="Msg_57f0aca83c6f"/>
  <wsdl:message name="Msg_c4f81fa3b53d"/>
  <wsdl:message name="Msg_b84d5f9726f0"/>
  <wsdl:message name="Msg_93ed396303ce"/>
  <wsdl:message name="Msg_a5305f0710d7"/>
  <wsdl:message name="Msg_302485662093"/>
  <wsdl:message name="Msg_49f202c9b73c"/>
  <wsdl:message name="Msg_9f3a49ebaed7"/>
  <wsdl:message name="Msg_b4a9751ac0a7"/>
  <wsdl:message name="Msg_c27eaab1e1e1"/>
  <wsdl:message name="Msg_dc70ed40d5bd"/>
  <wsdl:message name="Msg_6ba86fb0a4d1"/>
  <wsdl:message name="Msg_8dc008d6498f"/>
  <wsdl:message name="Msg_70835e93a808"/>
  <wsdl:message name="Msg_3891ebeda7c4"/>
  <wsdl:message name="Msg_f085374f4f49"/>
  <wsdl:message name="Msg_1e164bc1de43"/>
  <wsdl:message name="Msg_02e1494ad7df"/>
  <wsdl:message name="Msg_abb49790620a"/>
  <wsdl:message name="Msg_8d3040c1d5f1"/>
  <wsdl:message name="Msg_217f6aa56f5d"/>
  <wsdl:message name="Msg_f8769b7e4554"/>
  <wsdl:message name="Msg_1b4a6f109af8"/>
  <wsdl:message name="Msg_87ee9d83a2f5"/>
  <wsdl:message name="Msg_37d56a39d77f"/>
  <wsdl:message name="Msg_f0fd7728a01e"/>
  <wsdl:message name="Msg_7673b165e5f7"/>
  <wsdl:message name="Msg_402a95a047a9"/>
  <wsdl:message name="Msg_0f2b7eb004e6"/>
  <wsdl:message name="Msg_0f860685c9c8"/>
  <wsdl:message name="Msg_8f5c81d53643"/>
  <wsdl:message name="Msg_a4bb1b9bcac1"/>
  <wsdl:message name="Msg_2002ae4b8db8"/>
  <wsdl:message name="Msg_7f05bd5c9cd9"/>
  <wsdl:message name="Msg_61bfb415c31a"/>
  <wsdl:message name="Msg_27459a4702d8"/>
  <wsdl:message name="Msg_a61cccbee7af"/>
  <wsdl:message name="Msg_b6dae72cf60f"/>
  <wsdl:message name="Msg_13caa0f71a18"/>
  <wsdl:message name="Msg_b8d2a7754e46"/>
  <wsdl:message name="Msg_3b61e5c37f6f"/>
  <wsdl:message name="Msg_82c51bcd9dd2"/>
  <wsdl:message name="Msg_dbf0b6b3a35a"/>
  <wsdl:message name="Msg_c48009f99ffe"/>
  <wsdl:message name="Msg_7d50d8d86bf7"/>
  <wsdl:message name="Msg_52937dbf2e25"/>
  <wsdl:message name="Msg_016df9a1cd1c"/>
  <wsdl:message name="Msg_d0b23df98ef1"/>
  <wsdl:message name="Msg_9c2e8d9ac9ef"/>
  <wsdl:message name="Msg_cc7acfccab81"/>
  <wsdl:message name="Msg_6650ea6e93fa"/>
  <wsdl:message name="Msg_8e09f37b16a8"/>
  <wsdl:message name="Msg_0093f6115940"/>
  <wsdl:message name="Msg_067297900f99"/>
  <wsdl:message name="Msg_126789cecab5"/>
  <wsdl:message name="Msg_c55a3cd4aa00"/>
  <wsdl:message name="Msg_51a51abd4123"/>
  <wsdl:message name="Msg_f12b14c87501"/>
  <wsdl:message name="Msg_5837bb13aa0c"/>
  <wsdl:message name="Msg_279f6e3018bb"/>
  <wsdl:message name="Msg_5efee434b708"/>
  <wsdl:message name="Msg_3db9f260b507"/>
  <wsdl:message name="Msg_1cb063aa906b"/>
  <wsdl:message name="Msg_4a12058a4541"/>
  <wsdl:message name="Msg_9681f84482f6"/>
  <wsdl:message name="Msg_44007bf7a3d7"/>
  <wsdl:message name="Msg_a7b3f36397a1"/>
  <wsdl:message name="Msg_adc6c7f221d4"/>
  <wsdl:message name="Msg_7b6a3a2254df"/>
  <wsdl:message name="Msg_41a8fd4fac83"/>
  <wsdl:message name="Msg_a01521a72a33"/>
  <wsdl:message name="Msg_9d040d84540f"/>
  <wsdl:message name="Msg_ada414acfc58"/>
  <wsdl:message name="Msg_089d402c6f61"/>
  <wsdl:message name="Msg_6d9b55f91c24"/>
  <wsdl:message name="Msg_733fd947bec8"/>
  <wsdl:message name="Msg_a46f53e13b64"/>
  <wsdl:message name="Msg_d7269c5b38ae"/>
  <wsdl:message name="Msg_a782fbfdaa31"/>
  <wsdl:message name="Msg_50021ec5828f"/>
  <wsdl:message name="Msg_a1b9ed654044"/>
  <wsdl:message name="Msg_7811d356364d"/>
  <wsdl:message name="Msg_db2f45b49727"/>
  <wsdl:message name="Msg_a799330ef620"/>
  <wsdl:message name="Msg_14393619858d"/>
  <wsdl:message name="Msg_f44802149da3"/>
  <wsdl:message name="Msg_921e3919d7bb"/>
  <wsdl:message name="Msg_69bd8e6edf36"/>
  <wsdl:message name="Msg_23a4092cc6c3"/>
  <wsdl:message name="Msg_59fb8ca3e1a9"/>
  <wsdl:message name="Msg_34fac7d0cf22"/>
  <wsdl:message name="Msg_20dbb1aae2e9"/>
  <wsdl:message name="Msg_05555d6cdd89"/>
  <wsdl:message name="Msg_b9a419278202"/>
  <wsdl:message name="Msg_2af8a66bcb80"/>
  <wsdl:message name="Msg_c17a4b60d4df"/>
  <wsdl:message name="Msg_efc9f6312cfa"/>
  <wsdl:message name="Msg_ddcbad7bd342"/>
  <wsdl:message name="Msg_e078c5178a59"/>
</wsdl:definitions>
