<?xml version="1.0"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:message name="Msg_968d89fb3059"/>
  <wsdl:message name="Msg_5ea5e8808ecd"/>
  <wsdl:message name="Msg_ede4590373cf"/>
  <wsdl:message name="Msg_6c54544ddb85"/>
  <wsdl:message name="Msg_7b7f78e73c4d"/>
  <wsdl:message name="Msg_bc85ed28acfd"/>
  <wsdl:message name="Msg_c17fdc7baaea"/>
  <wsdl:message name="Msg_8e994763b796"/>
  <wsdl:message name="Msg_11ea06eb6e16"/>
  <wsdl:message name="Msg_6fa5f7b04387"/>
  <wsdl:message name="Msg_6bcd20ae74fd"/>
  <wsdl:message name="Msg_952cea9c9f1b"/>
  <wsdl:message name="Msg_b60a884945dc"/>
  <wsdl:message name="Msg_8bc3aaf64af7"/>
  <wsdl:message name="Msg_cbba12d68ad2"/>
  <wsdl:message name="Msg_027802d92476"/>
  <wsdl:message name="Msg_74f55a856db3"/>
  <wsdl:message name="Msg_47244726895f"/>
  <wsdl:message name="Msg_d0918b3463e9"/>
  <wsdl:message name="Msg_77796a053869"/>
  <wsdl:message name="Msg_92379313d853"/>
  <wsdl:message name="Msg_1223e05602ae"/>
  <wsdl:message name="Msg_f9655cc1b3e9"/>
  <wsdl:message name="Msg_cbf4b49f5936"/>
  <wsdl:message name="Msg_5da7ba452256"/>
  <wsdl:message name="Msg_9bfebe14c40c"/>
  <wsdl:message name="Msg_c0d52eab7cea"/>
  <wsdl:message name="Msg_e5d122122b4a"/>
  <wsdl:message name="Msg_aaa2e0bd299f"/>
  <wsdl:message name="Msg_fd819a45fc30"/>
  <wsdl:message name="Msg_fdae04013de4"/>
  <wsdl:message name="Msg_6d804b1e9d95"/>
  <wsdl:message name="Msg_c65bb1b0510c"/>
  <wsdl:message name="Msg_81d416dbac94"/>
  <wsdl:message name="Msg_407deca4d292"/>
  <wsdl:message name="Msg_798569aec277"/>
  <wsdl:message name="Msg_0354442cc683"/>
  <wsdl:message name="Msg_15202db328e4"/>
  <wsdl:message name="Msg_b237a862aaf8"/>
  <wsdl:message name="Msg_76f348a38226"/>
  <wsdl:message name="Msg_4385b81c6e21"/>
  <wsdl:message name="Msg_d81cabbc2462"/>
  <wsdl:message name="Msg_1f6c9685ad2f"/>
  <wsdl:message name="Msg_90ef9949cb79"/>
  <wsdl:message name="Msg_64ac2242d5c2"/>
  <wsdl:message name="Msg_febfde203b6e"/>
  <wsdl:message name="Msg_09c24e2ca505"/>
  <wsdl:message name="Msg_124c8e380969"/>
  <wsdl:message name="Msg_89fe5dc5581e"/>
  <wsdl:message name="Msg_f24fb240c4a0"/>
  <wsdl:message name="Msg_28fcbe9ea647"/>
  <wsdl:message name="Msg_c89984d130c5"/>
  <wsdl:message name="Msg_f628dd9fddd8"/>
  <wsdl:message name="Msg_23a0ce762548"/>
  <wsdl:message name="Msg_2fa177aae05f"/>
  <wsdl:message name="Msg_46f84eb02fb4"/>
  <wsdl:message name="Msg_9e7d24231988"/>
  <wsdl:message name="Msg_effe6f7247d7"/>
  <wsdl:message name="Msg_f495e6bd903a"/>
  <wsdl:message name="Msg_9a787bf39936"/>
  <wsdl:message name="Msg_39a00692492e"/>
  <wsdl:message name="Msg_d85edf87bf66"/>
  <wsdl:message name="Msg_6af6b54ad3e7"/>
  <wsdl:message name="Msg_743c77f2d73d"/>
  <wsdl:message name="Msg_1d5211105abc"/>
  <wsdl:message name="Msg_06908cd317ef"/>
  <wsdl:message name="Msg_f673f165ef17"/>
  <wsdl:message name="Msg_315a19309cfc"/>
  <wsdl:message name="Msg_ec3dda1ff968"/>
  <wsdl:message name="Msg_06c503b2fae1"/>
  <wsdl:message name="Msg_65defa471ed3"/>
  <wsdl:message name="Msg_bcd187e19777"/>
  <wsdl:message name="Msg_9e735164f159"/>
  <wsdl:message name="Msg_cebd93396c3c"/>
  <wsdl:message name="Msg_6292b81a3682"/>
  <wsdl:message name="Msg_c3537ab89e1d"/>
  <wsdl:message name="Msg_0b634a8970df"/>
  <wsdl:message name="Msg_bf033c01c0a5"/>
  <wsdl:message name="Msg_3c772ffa832f"/>
  <wsdl:message name="Msg_b4df9e88e30a"/>
  <wsdl:message name="Msg_0c1393526c29"/>
  <wsdl:message name="Msg_0dffe09664d1"/>
  <wsdl:message name="Msg_47b56e43bd2e"/>
  <wsdl:message name="Msg_2623bba6d37e"/>
  <wsdl:message name="Msg_cd0dd0b1750a"/>
  <wsdl:message name="Msg_78fcf9a7ea47"/>
  <wsdl:message name="Msg_63aaf95d9d09"/>
  <wsdl:message name="Msg_3dc18d97e08f"/>
  <wsdl:message name="Msg_ebdb1e9e3a52"/>
  <wsdl:message name="Msg_5fc34f06353e"/>
  <wsdl:message name="Msg_e2b8281cb350"/>
  <wsdl:message name="Msg_4ddaa77f647b"/>
  <wsdl:message name="Msg_947f194ab230"/>
  <wsdl:message name="Msg_2c6c8e009f86"/>
  <wsdl:message name="Msg_334f491b4e67"/>
  <wsdl:message name="Msg_744c312d2fc4"/>
  <wsdl:message name="Msg_d26b5b2ba021"/>
  <wsdl:message name="Msg_55149e936ee2"/>
  <wsdl:message name="Msg_01f2d8699625"/>
  <wsdl:message name="Msg_c22eb6498fc1"/>
  <wsdl:message name="Msg_81db38b0a4a0"/>
  <wsdl:message name="Msg_0f953999dcfe"/>
  <wsdl:message name="Msg_cc9bf8b297ee"/>
  <wsdl:message name="Msg_b617012aea89"/>
  <wsdl:message name="Msg_e09b4528c8b5"/>
  <wsdl:message name="Msg_7ceb5a9edc98"/>
  <wsdl:message name="Msg_2d63719f16d3"/>
  <wsdl:message name="Msg_b83adb6c8c8a"/>
  <wsdl:message name="Msg_5f230f07d703"/>
  <wsdl:message name="Msg_b1ffb3afe52c"/>
  <wsdl:message name="Msg_8d0b76c65558"/>
  <wsdl:message name="Msg_1bc223b4728e"/>
  <wsdl:message name="Msg_f92ca2c38e84"/>
  <wsdl:message name="Msg_b5e9c8ee79fb"/>
  <wsdl:message name="Msg_1d0887fe29f2"/>
  <wsdl:message name="Msg_6b64fc102e88"/>
  <wsdl:message name="Msg_dee5d1b2b74c"/>
  <wsdl:message name="Msg_7b9c419cc5b9"/>
  <wsdl:message name="Msg_fe2a04361f51"/>
  <wsdl:message name="Msg_862ef4e30de7"/>
  <wsdl:message name="Msg_08425e96aa28"/>
  <wsdl:message name="Msg_2e29ac6e28e9"/>
  <wsdl:message name="Msg_1d1918540678"/>
  <wsdl:message name="Msg_e22eacd08c68"/>
  <wsdl:message name="Msg_950536aa966c"/>
  <wsdl:message name="Msg_df9bf70bc3d6"/>
  <wsdl:message name="Msg_fdf2c9f978db"/>
  <wsdl:message name="Msg_689ea7c57263"/>
  <wsdl:message name="Msg_c225440940e0"/>
  <wsdl:message name="Msg_4e390e47d162"/>
  <wsdl:message name="Msg_bdc320c3bee4"/>
  <wsdl:message name="Msg_9c2ccf007412"/>
  <wsdl:message name="Msg_c7ff45e2b0ef"/>
  <wsdl:message name="Msg_3386d2f306a3"/>
  <wsdl:message name="Msg_d6875f976cd1"/>
  <wsdl:message name="Msg_7c6e08d69d67"/>
  <wsdl:message name="Msg_0a4fea632473"/>
  <wsdl:message name="Msg_55b6a718fdb1"/>
  <wsdl:message name="Msg_a64e536a3422"/>
  <wsdl:message name="Msg_5251c12cd6f9"/>
  <wsdl:message name="Msg_fe32bd16afd1"/>
  <wsdl:message name="Msg_8d20d5b2279e"/>
  <wsdl:message name="Msg_c50a35c8bb02"/>
  <wsdl:message name="Msg_15b1907c37e7"/>
  <wsdl:message name="Msg_a31e662b70e9"/>
  <wsdl:message name="Msg_d4c2e92b2dca"/>
  <wsdl:message name="Msg_bd2e8a4f4bb0"/>
  <wsdl:message name="Msg_e5ba5b0a7bf0"/>
  <wsdl:message name="Msg_ca8835265dbc"/>
  <wsdl:message name="Msg_aaef175e362a"/>
  <wsdl:message name="Msg_5ff5f1e8b1e8"/>
  <wsdl:message name="Msg_9a428e4ca462"/>
  <wsdl:message name="Msg_e682ee4e8f51"/>
  <wsdl:message name="Msg_1dd2a65109fa"/>
  <wsdl:message name="Msg_c0d44ec079ea"/>
  <wsdl:message name="Msg_60d87cae207c"/>
  <wsdl:message name="Msg_7106e7cd3f8c"/>
  <wsdl:message name="Msg_402898a3a83f"/>
  <wsdl:message name="Msg_b2cf5fe2636f"/>
  <wsdl:message name="Msg_938fb6275be2"/>
  <wsdl:message name="Msg_442469ebbfab"/>
  <wsdl:message name="Msg_e974462f73f5"/>
  <wsdl:message name="Msg_e37daac83422"/>
  <wsdl:message name="Msg_bf870fde2379"/>
  <wsdl:message name="Msg_c740e9132cea"/>
  <wsdl:message name="Msg_8b419814651c"/>
  <wsdl:message name="Msg_e4e7e4decb14"/>
  <wsdl:message name="Msg_3a1b6152d189"/>
  <wsdl:message name="Msg_c83612bcc40a"/>
  <wsdl:message name="Msg_28f1bd7dd822"/>
  <wsdl:message name="Msg_d397d6df1aa0"/>
  <wsdl:message name="Msg_6b68ede9ad1c"/>
  <wsdl:message name="Msg_0e722b01b3ac"/>
  <wsdl:message name="Msg_0ff820d8ea30"/>
  <wsdl:message name="Msg_05ba8c0c0707"/>
</wsdl:definitions>
