<?xml version="1.0"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:message name="Msg_991b2ef631e1"/>
  <wsdl:message name="Msg_1e6c1239c27f"/>
  <wsdl:message name="Msg_e243bd0e4714"/>
  <wsdl:message name="Msg_74f2bff7436f"/>
  <wsdl:message name="Msg_5fcdb53f1e0e"/>
  <wsdl:message name="Msg_a5318858d9fe"/>
  <wsdl:message name="Msg_dc2e794ab2ba"/>
  <wsdl:message name="Msg_e55f8decdd7a"/>
  <wsdl:message name="Msg_65ac8b14c35d"/>
  <wsdl:message name="Msg_e153849bb3e8"/>
  <wsdl:message name="Msg_28a23dae7c15"/>
  <wsdl:message name="Msg_f2e5dc2efae8"/>
  <wsdl:message name="Msg_e932d9e02501"/>
  <wsdl:message name="Msg_15830f42664c"/>
  <wsdl:message name="Msg_e67b7e5e526c"/>
  <wsdl:message name="Msg_adccdbf234d0"/>
  <wsdl:message name="Msg_c71dc7708a4f"/>
  <wsdl:message name="Msg_848eae33c1d2"/>
  <wsdl:message name="Msg_2df23b8db3b1"/>
  <wsdl:message name="Msg_774c87b7eceb"/>
  <wsdl:message name="Msg_07778effc786"/>
  <wsdl:message name="Msg_0df5ec8042a2"/>
  <wsdl:message name="Msg_acb4a955bab3"/>
  <wsdl:message name="Msg_4e2d859d7b81"/>
  <wsdl:message name="Msg_0f18d86b718c"/>
  <wsdl:message name="Msg_98b731d817c7"/>
  <wsdl:message name="Msg_bbaa242ab637"/>
  <wsdl:message name="Msg_c919a4b8eb0e"/>
  <wsdl:message name="Msg_8374eda0c09a"/>
  <wsdl:message name="Msg_109125385829"/>
  <wsdl:message name="Msg_14d4edd45716"/>
  <wsdl:message name="Msg_0f54dc7ecf93"/>
  <wsdl:message name="Msg_c3021bfaa63b"/>
  <wsdl:message name="Msg_b88236e53026"/>
  <wsdl:message name="Msg_06b3590cb951"/>
  <wsdl:message name="Msg_c0d7abb616d4"/>
  <wsdl:message name="Msg_25f9bca1d1cb"/>
  <wsdl:message name="Msg_9c2276d23c85"/>
  <wsdl:message name="Msg_463c54732bbf"/>
  <wsdl:message name="Msg_5e7b534421df"/>
  <wsdl:message name="Msg_8f65fa72e32b"/>
  <wsdl:message name="Msg_9791cc39f680"/>
  <wsdl:message name="Msg_2b57142b7332"/>
  <wsdl:message name="Msg_86554352c243"/>
  <wsdl:message name="Msg_15a24bfb4ccd"/>
  <wsdl:message name="Msg_4e794a8f5b6a"/>
  <wsdl:message name="Msg_c12b4fb4dffd"/>
  <wsdl:message name="Msg_635285942fd3"/>
  <wsdl:message name="Msg_feadae9ffb69"/>
  <wsdl:message name="Msg_c74a71cb9671"/>
  <wsdl:message name="Msg_e584bf90071b"/>
  <wsdl:message name="Msg_dc4fdb2b4ab9"/>
  <wsdl:message name="Msg_192cd146e758"/>
  <wsdl:message name="Msg_c8086d0a0e45"/>
  <wsdl:message name="Msg_91be98533004"/>
  <wsdl:message name="Msg_c91ce8b2992a"/>
  <wsdl:message name="Msg_e100b5b0fd9c"/>
  <wsdl:message name="Msg_ae625e9c90c8"/>
  <wsdl:message name="Msg_7c792701d0ba"/>
  <wsdl:message name="Msg_59198007584e"/>
  <wsdl:message name="Msg_4ff844a1cf0d"/>
  <wsdl:message name="Msg_3e2ccf22e3b5"/>
  <wsdl:message name="Msg_87b4a185de34"/>
  <wsdl:message name="Msg_d53a1a7cea18"/>
  <wsdl:message name="Msg_4d026efe16cb"/>
  <wsdl:message name="Msg_008acb759542"/>
  <wsdl:message name="Msg_5353d6df2a56"/>
  <wsdl:message name="Msg_c15b1908b77c"/>
  <wsdl:message name="Msg_2de0f22ab86c"/>
  <wsdl:message name="Msg_31dbcdfc92f1"/>
  <wsdl:message name="Msg_401312706143"/>
  <wsdl:message name="Msg_da0ccf8dd62a"/>
  <wsdl:message name="Msg_c49876e4aeed"/>
  <wsdl:message name="Msg_ef6b04505d9e"/>
  <wsdl:message name="Msg_3e2d4ffb897d"/>
  <wsdl:message name="Msg_eeb1369645dc"/>
  <wsdl:message name="Msg_6d7cca93481c"/>
  <wsdl:message name="Msg_1e9b89ce077e"/>
  <wsdl:message name="Msg_ad2c82e89c06"/>
  <wsdl:message name="Msg_3fe1003196f9"/>
  <wsdl:message name="Msg_e57fff8ca29b"/>
  <wsdl:message name="Msg_58bf6fcad73e"/>
  <wsdl:message name="Msg_e3e199f3d8cc"/>
  <wsdl:message name="Msg_f81f817e6f8d"/>
  <wsdl:message name="Msg_c9fa2651f79d"/>
  <wsdl:message name="Msg_eddef87f4b3b"/>
  <wsdl:message name="Msg_e2df098a520e"/>
  <wsdl:message name="Msg_eed544e277e9"/>
  <wsdl:message name="Msg_008396b1e99c"/>
  <wsdl:message name="Msg_77fa3f6761f3"/>
  <wsdl:message name="Msg_f45c8a1cad7c"/>
  <wsdl:message name="Msg_b4aee000092d"/>
  <wsdl:message name="Msg_c23a515b1316"/>
  <wsdl:message name="Msg_21810f5493de"/>
  <wsdl:message name="Msg_bbc8df2f108d"/>
  <wsdl:message name="Msg_e84f7e584335"/>
  <wsdl:message name="Msg_df5f263fabea"/>
  <wsdl:message name="Msg_14a5fe51f32b"/>
  <wsdl:message name="Msg_41cd5faf5153"/>
  <wsdl:message name="Msg_59497db0bd41"/>
  <wsdl:message name="Msg_baafa6dd6d7b"/>
  <wsdl:message name="Msg_63431ae49802"/>
  <wsdl:message name="Msg_c7eadeb6a19d"/>
  <wsdl:message name="Msg_4376649a5aa7"/>
  <wsdl:message name="Msg_ad0cebcaef9a"/>
  <wsdl:message name="Msg_716c5b9ddd2f"/>
  <wsdl:message name="Msg_763965c231ad"/>
  <wsdl:message name="Msg_949a243631a8"/>
  <wsdl:message name="Msg_098f790b5ad6"/>
  <wsdl:message name="Msg_3044d380137c"/>
  <wsdl:message name="Msg_3ad03ffa18fd"/>
  <wsdl:message name="Msg_d6b2e8c6d827"/>
  <wsdl:message name="Msg_1d128833668d"/>
  <wsdl:message name="Msg_343bd862f4aa"/>
  <wsdl:message name="Msg_747ce18f1e23"/>
  <wsdl:message name="Msg_2307d0516cfa"/>
  <wsdl:message name="Msg_41c2b7274735"/>
  <wsdl:message name="Msg_3b7f1a4a98f3"/>
  <wsdl:message name="Msg_6e9509056695"/>
  <wsdl:message name="Msg_006a0d240929"/>
  <wsdl:message name="Msg_4095ff59bd6f"/>
  <wsdl:message name="Msg_34ce48c12be0"/>
  <wsdl:message name="Msg_222ea3276475"/>
  <wsdl:message name="Msg_357a1c8efc8d"/>
  <wsdl:message name="Msg_888d37efdac6"/>
  <wsdl:message name="Msg_8ea3413b5524"/>
  <wsdl:message name="Msg_6d58ec0b5bb6"/>
  <wsdl:message name="Msg_79513b3d102b"/>
  <wsdl:message name="Msg_914899b198cd"/>
  <wsdl:message name="Msg_d5e363328c8b"/>
  <wsdl:message name="Msg_3950085481d0"/>
  <wsdl:message name="Msg_5f3b9a02c8ba"/>
  <wsdl:message name="Msg_194d5141eff5"/>
  <wsdl:message name="Msg_01834774763f"/>
  <wsdl:message name="Msg_00756af15da1"/>
  <wsdl:message name="Msg_d6ce58866538"/>
  <wsdl:message name="Msg_53ee2d99db65"/>
  <wsdl:message name="Msg_47a2d2e5499d"/>
  <wsdl:message name="Msg_f635573f6c55"/>
  <wsdl:message name="Msg_6a85b3824899"/>
  <wsdl:message name="Msg_146e1a387922"/>
  <wsdl:message name="Msg_483a26a1b610"/>
  <wsdl:message name="Msg_189a5fe4265c"/>
  <wsdl:message name="Msg_8bcfacc8c117"/>
  <wsdl:message name="Msg_d8afbc555706"/>
  <wsdl:message name="Msg_ffc1392f53cb"/>
  <wsdl:message name="Msg_fd383d3b42f9"/>
  <wsdl:message name="Msg_0982c85bb1ca"/>
  <wsdl:message name="Msg_73b1d5dca748"/>
  <wsdl:message name="Msg_9b3528877e1d"/>
  <wsdl:message name="Msg_5d69cd97a0d4"/>
  <wsdl:message name="Msg_56f00e9be1a2"/>
  <wsdl:message name="Msg_134fc2d6c1fe"/>
  <wsdl:message name="Msg_ea0dd4ce6702"/>
</wsdl:definitions>
