<?xml version="1.0"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:message name="Msg_8fff96cdfc7a"/>
  <wsdl:message name="Msg_1a186be902a9"/>
  <wsdl:message name="Msg_e7b4f83a923d"/>
  <wsdl:message name="Msg_316c179c60b1"/>
  <wsdl:message name="Msg_f1e159456e79"/>
  <wsdl:message name="Msg_c1b40d76ab04"/>
  <wsdl:message name="Msg_23d6d6e8e510"/>
  <wsdl:message name="Msg_fd80df31fe8b"/>
  <wsdl:message name="Msg_27aba898c7fc"/>
  <wsdl:message name="Msg_9bafeca77d76"/>
  <wsdl:message name="Msg_dd3163a275ec"/>
  <wsdl:message name="Msg_d281ea2ee54d"/>
  <wsdl:message name="Msg_8679a6e259fc"/>
  <wsdl:message name="Msg_175e0c37e97e"/>
  <wsdl:message name="Msg_a1f9f61af0c3"/>
  <wsdl:message name="Msg_bab996b26ba1"/>
  <wsdl:message name="Msg_ef1f5020658f"/>
  <wsdl:message name="Msg_26e35026078a"/>
  <wsdl:message name="Msg_54da9179302f"/>
  <wsdl:message name="Msg_9250f3bc9152"/>
  <wsdl:message name="Msg_ba2ca6cdc992"/>
  <wsdl:message name="Msg_c47a23ea553c"/>
  <wsdl:message name="Msg_d67fd8813da7"/>
  <wsdl:message name="Msg_e6a07a1ca97c"/>
  <wsdl:message name="Msg_9cb0af55ded4"/>
  <wsdl:message name="Msg_c58697b43bb2"/>
  <wsdl:message name="Msg_6fd976aa6563"/>
  <wsdl:message name="Msg_2f38c452e082"/>
  <wsdl:message name="Msg_9d60ddb6eec1"/>
  <wsdl:message name="Msg_74551fb8f00a"/>
  <wsdl:message name="Msg_28e55e675024"/>
  <wsdl:message name="Msg_5f4b8bbefaa8"/>
  <wsdl:message name="Msg_14b64d07cc73"/>
  <wsdl:message name="Msg_24409bb2388c"/>
  <wsdl:message name="Msg_a522f1f288f6"/>
  <wsdl:message name="Msg_d53802ae7c35"/>
  <wsdl:message name="Msg_1644c3d19aef"/>
  <wsdl:message name="Msg_54af5f8e690f"/>
  <wsdl:message name="Msg_60569a76cc4b"/>
  <wsdl:message name="Msg_88db197cf67e"/>
  <wsdl:message name="Msg_a28d3d48d333"/>
  <wsdl:message name="Msg_87939d827341"/>
  <wsdl:message name="Msg_4170052e1b76"/>
  <wsdl:message name="Msg_2af5912acfe3"/>
  <wsdl:message name="Msg_6ddb635ed7d6"/>
  <wsdl:message name="Msg_a01f604b576e"/>
  <wsdl:message name="Msg_02aa4d0c27ec"/>
  <wsdl:message name="Msg_14caf55258b0"/>
  <wsdl:message name="Msg_faa91d78c461"/>
  <wsdl:message name="Msg_2f75463ccf47"/>
  <wsdl:message name="Msg_485eb551c401"/>
  <wsdl:message name="Msg_b84d610edb01"/>
  <wsdl:message name="Msg_492ef9caa2c6"/>
  <wsdl:message name="Msg_b0a2753fc66c"/>
  <wsdl:message name="Msg_9946cfb5e05f"/>
  <wsdl:message name="Msg_5d94eb21a587"/>
  <wsdl:message name="Msg_7d95a3689251"/>
  <wsdl:message name="Msg_4b9fb4499d8b"/>
  <wsdl:message name="Msg_1b62b8db255f"/>
  <wsdl:message name="Msg_bac73ce5f05e"/>
  <wsdl:message name="Msg_4a6896df0397"/>
  <wsdl:message name="Msg_d61e37cf4e3a"/>
  <wsdl:message name="Msg_9342df721a2e"/>
  <wsdl:message name="Msg_82d5b455a55b"/>
  <wsdl:message name="Msg_83532e128456"/>
  <wsdl:message name="Msg_b2a149e670cb"/>
  <wsdl:message name="Msg_bc11f62e7d37"/>
  <wsdl:message name="Msg_e994141844b7"/>
  <wsdl:message name="Msg_93967badf566"/>
  <wsdl:message name="Msg_d07da28127fe"/>
</wsdl:definitions>
