<?xml version="1.0"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:message name="Msg_7924dd9c1306"/>
  <wsdl:message name="Msg_12ad4ba2eb60"/>
  <wsdl:message name="Msg_e26645247af4"/>
  <wsdl:message name="Msg_e860821f3575"/>
  <wsdl:message name="Msg_80951fc50bef"/>
  <wsdl:message name="Msg_904ff72a8bbe"/>
  <wsdl:message name="Msg_f9f6428609e4"/>
  <wsdl:message name="Msg_b9090960038c"/>
  <wsdl:message name="Msg_6b53ddd376d5"/>
  <wsdl:message name="Msg_ea6113711022"/>
  <wsdl:message name="Msg_5cf196a08191"/>
  <wsdl:message name="Msg_115f7371916c"/>
  <wsdl:message name="Msg_26c3058f4d3d"/>
  <wsdl:message name="Msg_8fb86a9254b9"/>
  <wsdl:message name="Msg_e5b22e0b967c"/>
  <wsdl:message name="Msg_1a463ed8db2d"/>
  <wsdl:message name="Msg_ea9356eb7fcb"/>
  <wsdl:message name="Msg_b2a2fd00d4cb"/>
  <wsdl:message name="Msg_d12b01ab1d7e"/>
  <wsdl:message name="Msg_f1bbb21e137a"/>
  <wsdl:message name="Msg_daaf3784965b"/>
  <wsdl:message name="Msg_de7d14b47efb"/>
  <wsdl:message name="Msg_0ab4fa8607eb"/>
  <wsdl:message name="Msg_37e669795a40"/>
  <wsdl:message name="Msg_b9a86794a043"/>
  <wsdl:message name="Msg_4711e50735dd"/>
  <wsdl:message name="Msg_5e21dd3e324f"/>
  <wsdl:message name="Msg_57a25d305cfc"/>
  <wsdl:message name="Msg_19a8097f1ea7"/>
  <wsdl:message name="Msg_6da29f529d81"/>
  <wsdl:message name="Msg_3c4966348720"/>
  <wsdl:message name="Msg_8774c573ef61"/>
  <wsdl:message name="Msg_47960e24d200"/>
  <wsdl:message name="Msg_84c0a14b9814"/>
  <wsdl:message name="Msg_1d9417c0c522"/>
  <wsdl:message name="Msg_fcc0d7e67c56"/>
  <wsdl:message name="Msg_3d08401550e2"/>
  <wsdl:message name="Msg_c6f203314c6a"/>
  <wsdl:message name="Msg_c645a855469b"/>
  <wsdl:message name="Msg_9054dfa12600"/>
  <wsdl:message name="Msg_ee5763187a30"/>
  <wsdl:message name="Msg_029c6544fb9d"/>
  <wsdl:message name="Msg_089a8609a347"/>
  <wsdl:message name="Msg_827b315c96d7"/>
  <wsdl:message name="Msg_be9fca430a94"/>
  <wsdl:message name="Msg_f129d25ab739"/>
  <wsdl:message name="Msg_b98c68e7a821"/>
  <wsdl:message name="Msg_cd8d9b600524"/>
  <wsdl:message name="Msg_4af2ddfc36ae"/>
  <wsdl:message name="Msg_eef224f380f2"/>
  <wsdl:message name="Msg_2dc2b7a0b827"/>
  <wsdl:message name="Msg_cdd519d8e170"/>
  <wsdl:message name="Msg_07d7d6c88507"/>
  <wsdl:message name="Msg_1d6439bc8354"/>
  <wsdl:message name="Msg_a9ea3d9617f6"/>
  <wsdl:message name="Msg_8d6949e90b2b"/>
  <wsdl:message name="Msg_c57f787db509"/>
  <wsdl:message name="Msg_83622cc34a12"/>
  <wsdl:message name="Msg_11a301fb0998"/>
  <wsdl:message name="Msg_05083dc61173"/>
  <wsdl:message name="Msg_d675906b594d"/>
  <wsdl:message name="Msg_8c826b77e5cf"/>
  <wsdl:message name="Msg_2cd001c141fd"/>
  <wsdl:message name="Msg_6203c3313b9a"/>
  <wsdl:message name="Msg_b5b8f1876295"/>
  <wsdl:message name="Msg_266e0256ed65"/>
  <wsdl:message name="Msg_176d67fff2a2"/>
  <wsdl:message name="Msg_28f6cd7c79cd"/>
  <wsdl:message name="Msg_f5531dbd0988"/>
  <wsdl:message name="Msg_af52aad79dd6"/>
  <wsdl:message name="Msg_38832114960a"/>
  <wsdl:message name="Msg_c5d6e3ef01c0"/>
  <wsdl:message name="Msg_5238b06242e3"/>
  <wsdl:message name="Msg_d481ab08d921"/>
  <wsdl:message name="Msg_1bb0e70888b5"/>
  <wsdl:message name="Msg_6921bbc9e8d4"/>
  <wsdl:message name="Msg_a9d97f7fbe44"/>
  <wsdl:message name="Msg_72a714a4b97c"/>
  <wsdl:message name="Msg_89914cb8e16c"/>
  <wsdl:message name="Msg_8019d9cb4769"/>
  <wsdl:message name="Msg_97f92633c3d0"/>
  <wsdl:message name="Msg_4b764e6a1295"/>
  <wsdl:message name="Msg_d91c94a1d11e"/>
  <wsdl:message name="Msg_29547d8cde8d"/>
  <wsdl:message name="Msg_b1c9efacd8bf"/>
  <wsdl:message name="Msg_f03e66848459"/>
  <wsdl:message name="Msg_830f3065a582"/>
  <wsdl:message name="Msg_1805510e5491"/>
  <wsdl:message name="Msg_7f77d47748ce"/>
  <wsdl:message name="Msg_2630613220f1"/>
  <wsdl:message name="Msg_9049eb713e43"/>
  <wsdl:message name="Msg_3d583c19581d"/>
  <wsdl:message name="Msg_b699d3846cf8"/>
  <wsdl:message name="Msg_1ae3ab5e6938"/>
  <wsdl:message name="Msg_5e70a81b97f7"/>
  <wsdl:message name="Msg_fd2a9ae1a679"/>
  <wsdl:message name="Msg_7ae14e81eaf0"/>
  <wsdl:message name="Msg_904f1f5e69ae"/>
  <wsdl:message name="Msg_4d5bf2ef5ba5"/>
  <wsdl:message name="Msg_20108062bae3"/>
  <wsdl:message name="Msg_6970f5ec5d7f"/>
  <wsdl:message name="Msg_04e45964c53c"/>
  <wsdl:message name="Msg_8061ee528380"/>
  <wsdl:message name="Msg_f9590bf68c5e"/>
  <wsdl:message name="Msg_3324403e6b96"/>
  <wsdl:message name="Msg_e62147f8b39d"/>
  <wsdl:message name="Msg_358b801aff72"/>
  <wsdl:message name="Msg_e772f3f699d1"/>
  <wsdl:message name="Msg_91d2d86a0d3d"/>
  <wsdl:message name="Msg_7452c915a6e9"/>
  <wsdl:message name="Msg_83317b809a30"/>
  <wsdl:message name="Msg_ff09ec4d5511"/>
  <wsdl:message name="Msg_f5cf0ec67a13"/>
  <wsdl:message name="Msg_942466bfd49e"/>
  <wsdl:message name="Msg_256f1f6216bb"/>
  <wsdl:message name="Msg_be504e90c318"/>
  <wsdl:message name="Msg_3fd1debaf160"/>
  <wsdl:message name="Msg_e2e48948ae52"/>
  <wsdl:message name="Msg_881a44dbf3ad"/>
  <wsdl:message name="Msg_61520225848f"/>
  <wsdl:message name="Msg_bd2c39c37bf8"/>
  <wsdl:message name="Msg_09de3623a021"/>
  <wsdl:message name="Msg_11599ba37bdf"/>
  <wsdl:message name="Msg_a145d2de6d4b"/>
  <wsdl:message name="Msg_26ecde3de3ba"/>
  <wsdl:message name="Msg_638236458303"/>
  <wsdl:message name="Msg_72c882357af8"/>
  <wsdl:message name="Msg_c2af94476802"/>
  <wsdl:message name="Msg_684f3a33402b"/>
  <wsdl:message name="Msg_cbda4d5bccfe"/>
  <wsdl:message name="Msg_1aa2cb6f2b8d"/>
  <wsdl:message name="Msg_02e3c3ae4e2f"/>
  <wsdl:message name="Msg_40a791547938"/>
  <wsdl:message name="Msg_001fd49e3ed2"/>
  <wsdl:message name="Msg_329329dbb779"/>
  <wsdl:message name="Msg_ed8126055cc1"/>
  <wsdl:message name="Msg_f544020c4710"/>
  <wsdl:message name="Msg_30487fb70e07"/>
  <wsdl:message name="Msg_e9bd94653855"/>
  <wsdl:message name="Msg_74355041bea0"/>
  <wsdl:message name="Msg_a3099bd9a32f"/>
  <wsdl:message name="Msg_49024bf865b3"/>
  <wsdl:message name="Msg_9a6f5eaccd72"/>
  <wsdl:message name="Msg_4b6ee0752bb6"/>
  <wsdl:message name="Msg_6ebc05e28eaa"/>
  <wsdl:message name="Msg_2b9a5aa8fc0c"/>
  <wsdl:message name="Msg_fc4f1c45982a"/>
  <wsdl:message name="Msg_e05177090728"/>
  <wsdl:message name="Msg_57ba14a0f829"/>
  <wsdl:message name="Msg_cde2e2c1486a"/>
  <wsdl:message name="Msg_fed1be591a82"/>
  <wsdl:message name="Msg_cf54c1f37fce"/>
  <wsdl:message name="Msg_ad687b2ffbfe"/>
  <wsdl:message name="Msg_915c36b9a852"/>
  <wsdl:message name="Msg_f09f88cb6a60"/>
  <wsdl:message name="Msg_3abcbf3adaf3"/>
  <wsdl:message name="Msg_b0cacbc6a92e"/>
</wsdl:definitions>
